// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mmpay.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ActionAttr;
@class Address;
@class BaseRequest;
@class BaseResponse;
@class Discount;
@class Express;
@class KVItem;
@class Production;
@class RcptInfoList;
@class RcptInfoNode;
@class Receipt;
@class SKBuiltinBuffer_t;
@class SKBuiltinString_t;
@class SampleProduct;
@class Snapshot;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MmpayRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MmpayRoot : GPBRootObject
@end

#pragma mark - RcptInfoNode

typedef GPB_ENUM(RcptInfoNode_FieldNumber) {
  RcptInfoNode_FieldNumber_Id_p = 1,
  RcptInfoNode_FieldNumber_Country = 2,
  RcptInfoNode_FieldNumber_Province = 3,
  RcptInfoNode_FieldNumber_City = 4,
  RcptInfoNode_FieldNumber_District = 5,
  RcptInfoNode_FieldNumber_Zipcode = 6,
  RcptInfoNode_FieldNumber_Detail = 7,
  RcptInfoNode_FieldNumber_Name = 8,
  RcptInfoNode_FieldNumber_Phone = 9,
  RcptInfoNode_FieldNumber_NationalcodeGbt2260 = 10,
};

@interface RcptInfoNode : GPBMessage

@property(nonatomic, readwrite) uint32_t id_p;

@property(nonatomic, readwrite) BOOL hasId_p;
@property(nonatomic, readwrite, strong, null_resettable) SKBuiltinString_t *country;
/** Test to see if @c country has been set. */
@property(nonatomic, readwrite) BOOL hasCountry;

@property(nonatomic, readwrite, strong, null_resettable) SKBuiltinString_t *province;
/** Test to see if @c province has been set. */
@property(nonatomic, readwrite) BOOL hasProvince;

@property(nonatomic, readwrite, strong, null_resettable) SKBuiltinString_t *city;
/** Test to see if @c city has been set. */
@property(nonatomic, readwrite) BOOL hasCity;

@property(nonatomic, readwrite, strong, null_resettable) SKBuiltinString_t *district;
/** Test to see if @c district has been set. */
@property(nonatomic, readwrite) BOOL hasDistrict;

@property(nonatomic, readwrite, strong, null_resettable) SKBuiltinString_t *zipcode;
/** Test to see if @c zipcode has been set. */
@property(nonatomic, readwrite) BOOL hasZipcode;

@property(nonatomic, readwrite, strong, null_resettable) SKBuiltinString_t *detail;
/** Test to see if @c detail has been set. */
@property(nonatomic, readwrite) BOOL hasDetail;

@property(nonatomic, readwrite, strong, null_resettable) SKBuiltinString_t *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

@property(nonatomic, readwrite, strong, null_resettable) SKBuiltinString_t *phone;
/** Test to see if @c phone has been set. */
@property(nonatomic, readwrite) BOOL hasPhone;

@property(nonatomic, readwrite, strong, null_resettable) SKBuiltinString_t *nationalcodeGbt2260;
/** Test to see if @c nationalcodeGbt2260 has been set. */
@property(nonatomic, readwrite) BOOL hasNationalcodeGbt2260;

@end

#pragma mark - RcptInfoList

typedef GPB_ENUM(RcptInfoList_FieldNumber) {
  RcptInfoList_FieldNumber_Count = 1,
  RcptInfoList_FieldNumber_RcptinfolistArray = 2,
  RcptInfoList_FieldNumber_Timestamp = 3,
};

@interface RcptInfoList : GPBMessage

@property(nonatomic, readwrite) uint32_t count;

@property(nonatomic, readwrite) BOOL hasCount;
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<RcptInfoNode*> *rcptinfolistArray;
/** The number of items in @c rcptinfolistArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger rcptinfolistArray_Count;

@property(nonatomic, readwrite) uint32_t timestamp;

@property(nonatomic, readwrite) BOOL hasTimestamp;
@end

#pragma mark - RcptInfoAddRequest

typedef GPB_ENUM(RcptInfoAddRequest_FieldNumber) {
  RcptInfoAddRequest_FieldNumber_BaseRequest = 1,
  RcptInfoAddRequest_FieldNumber_Rcptinfo = 2,
};

@interface RcptInfoAddRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseRequest *baseRequest;
/** Test to see if @c baseRequest has been set. */
@property(nonatomic, readwrite) BOOL hasBaseRequest;

@property(nonatomic, readwrite, strong, null_resettable) RcptInfoNode *rcptinfo;
/** Test to see if @c rcptinfo has been set. */
@property(nonatomic, readwrite) BOOL hasRcptinfo;

@end

#pragma mark - RcptInfoAddResponse

typedef GPB_ENUM(RcptInfoAddResponse_FieldNumber) {
  RcptInfoAddResponse_FieldNumber_Rcptinfolist = 1,
  RcptInfoAddResponse_FieldNumber_BaseResponse = 2,
};

@interface RcptInfoAddResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RcptInfoList *rcptinfolist;
/** Test to see if @c rcptinfolist has been set. */
@property(nonatomic, readwrite) BOOL hasRcptinfolist;

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@end

#pragma mark - RcptInfoRemoveRequest

typedef GPB_ENUM(RcptInfoRemoveRequest_FieldNumber) {
  RcptInfoRemoveRequest_FieldNumber_BaseRequest = 1,
  RcptInfoRemoveRequest_FieldNumber_Id_p = 2,
};

@interface RcptInfoRemoveRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseRequest *baseRequest;
/** Test to see if @c baseRequest has been set. */
@property(nonatomic, readwrite) BOOL hasBaseRequest;

@property(nonatomic, readwrite) uint32_t id_p;

@property(nonatomic, readwrite) BOOL hasId_p;
@end

#pragma mark - RcptInfoRemoveResponse

typedef GPB_ENUM(RcptInfoRemoveResponse_FieldNumber) {
  RcptInfoRemoveResponse_FieldNumber_Id_p = 1,
  RcptInfoRemoveResponse_FieldNumber_Rcptinfolist = 2,
  RcptInfoRemoveResponse_FieldNumber_BaseResponse = 3,
};

@interface RcptInfoRemoveResponse : GPBMessage

@property(nonatomic, readwrite) uint32_t id_p;

@property(nonatomic, readwrite) BOOL hasId_p;
@property(nonatomic, readwrite, strong, null_resettable) RcptInfoList *rcptinfolist;
/** Test to see if @c rcptinfolist has been set. */
@property(nonatomic, readwrite) BOOL hasRcptinfolist;

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@end

#pragma mark - RcptInfoQueryRequest

typedef GPB_ENUM(RcptInfoQueryRequest_FieldNumber) {
  RcptInfoQueryRequest_FieldNumber_BaseRequest = 1,
  RcptInfoQueryRequest_FieldNumber_Timestamp = 2,
  RcptInfoQueryRequest_FieldNumber_Webviewurl = 3,
  RcptInfoQueryRequest_FieldNumber_Appid = 4,
  RcptInfoQueryRequest_FieldNumber_Scene = 5,
};

@interface RcptInfoQueryRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseRequest *baseRequest;
/** Test to see if @c baseRequest has been set. */
@property(nonatomic, readwrite) BOOL hasBaseRequest;

@property(nonatomic, readwrite) uint32_t timestamp;

@property(nonatomic, readwrite) BOOL hasTimestamp;
@property(nonatomic, readwrite, copy, null_resettable) NSString *webviewurl;
/** Test to see if @c webviewurl has been set. */
@property(nonatomic, readwrite) BOOL hasWebviewurl;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appid;
/** Test to see if @c appid has been set. */
@property(nonatomic, readwrite) BOOL hasAppid;

@property(nonatomic, readwrite) uint32_t scene;

@property(nonatomic, readwrite) BOOL hasScene;
@end

#pragma mark - RcptInfoQueryResponse

typedef GPB_ENUM(RcptInfoQueryResponse_FieldNumber) {
  RcptInfoQueryResponse_FieldNumber_Rcptinfolist = 1,
  RcptInfoQueryResponse_FieldNumber_Islatest = 2,
  RcptInfoQueryResponse_FieldNumber_BaseResponse = 3,
  RcptInfoQueryResponse_FieldNumber_Appusername = 4,
  RcptInfoQueryResponse_FieldNumber_Isauthority = 5,
  RcptInfoQueryResponse_FieldNumber_Appnickname = 6,
};

@interface RcptInfoQueryResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RcptInfoList *rcptinfolist;
/** Test to see if @c rcptinfolist has been set. */
@property(nonatomic, readwrite) BOOL hasRcptinfolist;

@property(nonatomic, readwrite) uint32_t islatest;

@property(nonatomic, readwrite) BOOL hasIslatest;
@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appusername;
/** Test to see if @c appusername has been set. */
@property(nonatomic, readwrite) BOOL hasAppusername;

@property(nonatomic, readwrite) uint32_t isauthority;

@property(nonatomic, readwrite) BOOL hasIsauthority;
@property(nonatomic, readwrite, copy, null_resettable) NSString *appnickname;
/** Test to see if @c appnickname has been set. */
@property(nonatomic, readwrite) BOOL hasAppnickname;

@end

#pragma mark - RcptInfoUpdateRequest

typedef GPB_ENUM(RcptInfoUpdateRequest_FieldNumber) {
  RcptInfoUpdateRequest_FieldNumber_BaseRequest = 1,
  RcptInfoUpdateRequest_FieldNumber_Rcptinfo = 2,
};

@interface RcptInfoUpdateRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseRequest *baseRequest;
/** Test to see if @c baseRequest has been set. */
@property(nonatomic, readwrite) BOOL hasBaseRequest;

@property(nonatomic, readwrite, strong, null_resettable) RcptInfoNode *rcptinfo;
/** Test to see if @c rcptinfo has been set. */
@property(nonatomic, readwrite) BOOL hasRcptinfo;

@end

#pragma mark - RcptInfoUpdateResponse

typedef GPB_ENUM(RcptInfoUpdateResponse_FieldNumber) {
  RcptInfoUpdateResponse_FieldNumber_Rcptinfolist = 1,
  RcptInfoUpdateResponse_FieldNumber_BaseResponse = 2,
};

@interface RcptInfoUpdateResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RcptInfoList *rcptinfolist;
/** Test to see if @c rcptinfolist has been set. */
@property(nonatomic, readwrite) BOOL hasRcptinfolist;

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@end

#pragma mark - RcptInfoTouchRequest

typedef GPB_ENUM(RcptInfoTouchRequest_FieldNumber) {
  RcptInfoTouchRequest_FieldNumber_BaseRequest = 1,
  RcptInfoTouchRequest_FieldNumber_Id_p = 2,
};

@interface RcptInfoTouchRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseRequest *baseRequest;
/** Test to see if @c baseRequest has been set. */
@property(nonatomic, readwrite) BOOL hasBaseRequest;

@property(nonatomic, readwrite) uint32_t id_p;

@property(nonatomic, readwrite) BOOL hasId_p;
@end

#pragma mark - RcptInfoTouchResponse

typedef GPB_ENUM(RcptInfoTouchResponse_FieldNumber) {
  RcptInfoTouchResponse_FieldNumber_Rcptinfolist = 1,
  RcptInfoTouchResponse_FieldNumber_BaseResponse = 2,
};

@interface RcptInfoTouchResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RcptInfoList *rcptinfolist;
/** Test to see if @c rcptinfolist has been set. */
@property(nonatomic, readwrite) BOOL hasRcptinfolist;

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@end

#pragma mark - RcptInfoImportYiXunRequest

typedef GPB_ENUM(RcptInfoImportYiXunRequest_FieldNumber) {
  RcptInfoImportYiXunRequest_FieldNumber_BaseRequest = 1,
  RcptInfoImportYiXunRequest_FieldNumber_Qq = 2,
  RcptInfoImportYiXunRequest_FieldNumber_A2Key = 3,
  RcptInfoImportYiXunRequest_FieldNumber_NewA2Key = 4,
};

@interface RcptInfoImportYiXunRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseRequest *baseRequest;
/** Test to see if @c baseRequest has been set. */
@property(nonatomic, readwrite) BOOL hasBaseRequest;

@property(nonatomic, readwrite) uint32_t qq;

@property(nonatomic, readwrite) BOOL hasQq;
@property(nonatomic, readwrite, strong, null_resettable) SKBuiltinBuffer_t *a2Key;
/** Test to see if @c a2Key has been set. */
@property(nonatomic, readwrite) BOOL hasA2Key;

@property(nonatomic, readwrite, strong, null_resettable) SKBuiltinBuffer_t *newA2Key NS_RETURNS_NOT_RETAINED;
/** Test to see if @c newA2Key has been set. */
@property(nonatomic, readwrite) BOOL hasNewA2Key;

@end

#pragma mark - RcptInfoImportYiXunResponse

typedef GPB_ENUM(RcptInfoImportYiXunResponse_FieldNumber) {
  RcptInfoImportYiXunResponse_FieldNumber_Rcptinfolist = 1,
  RcptInfoImportYiXunResponse_FieldNumber_Rcptinfoimportstatus = 2,
  RcptInfoImportYiXunResponse_FieldNumber_BaseResponse = 3,
};

@interface RcptInfoImportYiXunResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RcptInfoList *rcptinfolist;
/** Test to see if @c rcptinfolist has been set. */
@property(nonatomic, readwrite) BOOL hasRcptinfolist;

@property(nonatomic, readwrite) int32_t rcptinfoimportstatus;

@property(nonatomic, readwrite) BOOL hasRcptinfoimportstatus;
@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@end

#pragma mark - GenBizIapPrepayRequest

typedef GPB_ENUM(GenBizIapPrepayRequest_FieldNumber) {
  GenBizIapPrepayRequest_FieldNumber_BaseRequest = 1,
  GenBizIapPrepayRequest_FieldNumber_AppId = 2,
  GenBizIapPrepayRequest_FieldNumber_NonceStr = 3,
  GenBizIapPrepayRequest_FieldNumber_TimeStamp = 4,
  GenBizIapPrepayRequest_FieldNumber_Package = 5,
  GenBizIapPrepayRequest_FieldNumber_PaySign = 6,
  GenBizIapPrepayRequest_FieldNumber_SignType = 7,
  GenBizIapPrepayRequest_FieldNumber_StepInURL = 8,
};

@interface GenBizIapPrepayRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseRequest *baseRequest;
/** Test to see if @c baseRequest has been set. */
@property(nonatomic, readwrite) BOOL hasBaseRequest;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;
/** Test to see if @c appId has been set. */
@property(nonatomic, readwrite) BOOL hasAppId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nonceStr;
/** Test to see if @c nonceStr has been set. */
@property(nonatomic, readwrite) BOOL hasNonceStr;

@property(nonatomic, readwrite, copy, null_resettable) NSString *timeStamp;
/** Test to see if @c timeStamp has been set. */
@property(nonatomic, readwrite) BOOL hasTimeStamp;

@property(nonatomic, readwrite, copy, null_resettable) NSString *package;
/** Test to see if @c package has been set. */
@property(nonatomic, readwrite) BOOL hasPackage;

@property(nonatomic, readwrite, copy, null_resettable) NSString *paySign;
/** Test to see if @c paySign has been set. */
@property(nonatomic, readwrite) BOOL hasPaySign;

@property(nonatomic, readwrite, copy, null_resettable) NSString *signType;
/** Test to see if @c signType has been set. */
@property(nonatomic, readwrite) BOOL hasSignType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *stepInURL;
/** Test to see if @c stepInURL has been set. */
@property(nonatomic, readwrite) BOOL hasStepInURL;

@end

#pragma mark - GenBizIapPrepayResponse

typedef GPB_ENUM(GenBizIapPrepayResponse_FieldNumber) {
  GenBizIapPrepayResponse_FieldNumber_BaseResponse = 1,
  GenBizIapPrepayResponse_FieldNumber_ProductId = 2,
  GenBizIapPrepayResponse_FieldNumber_ExtInfo = 4,
};

@interface GenBizIapPrepayResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@property(nonatomic, readwrite, copy, null_resettable) NSString *productId;
/** Test to see if @c productId has been set. */
@property(nonatomic, readwrite) BOOL hasProductId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *extInfo;
/** Test to see if @c extInfo has been set. */
@property(nonatomic, readwrite) BOOL hasExtInfo;

@end

#pragma mark - GetBizIapPayResultRequest

typedef GPB_ENUM(GetBizIapPayResultRequest_FieldNumber) {
  GetBizIapPayResultRequest_FieldNumber_BaseRequest = 1,
  GetBizIapPayResultRequest_FieldNumber_SerialId = 2,
};

@interface GetBizIapPayResultRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseRequest *baseRequest;
/** Test to see if @c baseRequest has been set. */
@property(nonatomic, readwrite) BOOL hasBaseRequest;

@property(nonatomic, readwrite, copy, null_resettable) NSString *serialId;
/** Test to see if @c serialId has been set. */
@property(nonatomic, readwrite) BOOL hasSerialId;

@end

#pragma mark - GetBizIapPayResultResponse

typedef GPB_ENUM(GetBizIapPayResultResponse_FieldNumber) {
  GetBizIapPayResultResponse_FieldNumber_BaseResponse = 1,
  GetBizIapPayResultResponse_FieldNumber_DetailBuff = 2,
};

@interface GetBizIapPayResultResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@property(nonatomic, readwrite, copy, null_resettable) NSString *detailBuff;
/** Test to see if @c detailBuff has been set. */
@property(nonatomic, readwrite) BOOL hasDetailBuff;

@end

#pragma mark - GetBizIapDetailRequest

typedef GPB_ENUM(GetBizIapDetailRequest_FieldNumber) {
  GetBizIapDetailRequest_FieldNumber_BaseRequest = 1,
  GetBizIapDetailRequest_FieldNumber_SerialId = 3,
};

@interface GetBizIapDetailRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseRequest *baseRequest;
/** Test to see if @c baseRequest has been set. */
@property(nonatomic, readwrite) BOOL hasBaseRequest;

@property(nonatomic, readwrite, copy, null_resettable) NSString *serialId;
/** Test to see if @c serialId has been set. */
@property(nonatomic, readwrite) BOOL hasSerialId;

@end

#pragma mark - GetBizIapDetailResponse

typedef GPB_ENUM(GetBizIapDetailResponse_FieldNumber) {
  GetBizIapDetailResponse_FieldNumber_BaseResponse = 1,
  GetBizIapDetailResponse_FieldNumber_DetailBuff = 2,
};

@interface GetBizIapDetailResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@property(nonatomic, readwrite, copy, null_resettable) NSString *detailBuff;
/** Test to see if @c detailBuff has been set. */
@property(nonatomic, readwrite) BOOL hasDetailBuff;

@end

#pragma mark - GetProductDetailRequest

typedef GPB_ENUM(GetProductDetailRequest_FieldNumber) {
  GetProductDetailRequest_FieldNumber_BaseRequest = 1,
  GetProductDetailRequest_FieldNumber_Pid = 2,
  GetProductDetailRequest_FieldNumber_Version = 3,
  GetProductDetailRequest_FieldNumber_ScanCode = 4,
};

@interface GetProductDetailRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseRequest *baseRequest;
/** Test to see if @c baseRequest has been set. */
@property(nonatomic, readwrite) BOOL hasBaseRequest;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pid;
/** Test to see if @c pid has been set. */
@property(nonatomic, readwrite) BOOL hasPid;

@property(nonatomic, readwrite) uint32_t version;

@property(nonatomic, readwrite) BOOL hasVersion;
@property(nonatomic, readwrite, copy, null_resettable) NSString *scanCode;
/** Test to see if @c scanCode has been set. */
@property(nonatomic, readwrite) BOOL hasScanCode;

@end

#pragma mark - GetProductDetailResponse

typedef GPB_ENUM(GetProductDetailResponse_FieldNumber) {
  GetProductDetailResponse_FieldNumber_BaseResponse = 1,
  GetProductDetailResponse_FieldNumber_ProductInfo = 2,
  GetProductDetailResponse_FieldNumber_RetCode = 3,
  GetProductDetailResponse_FieldNumber_RetMsg = 4,
  GetProductDetailResponse_FieldNumber_RecommendInfo = 5,
};

@interface GetProductDetailResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@property(nonatomic, readwrite, copy, null_resettable) NSString *productInfo;
/** Test to see if @c productInfo has been set. */
@property(nonatomic, readwrite) BOOL hasProductInfo;

@property(nonatomic, readwrite) int32_t retCode;

@property(nonatomic, readwrite) BOOL hasRetCode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retMsg;
/** Test to see if @c retMsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetMsg;

@property(nonatomic, readwrite, copy, null_resettable) NSString *recommendInfo;
/** Test to see if @c recommendInfo has been set. */
@property(nonatomic, readwrite) BOOL hasRecommendInfo;

@end

#pragma mark - LockStockRequest

typedef GPB_ENUM(LockStockRequest_FieldNumber) {
  LockStockRequest_FieldNumber_BaseRequest = 1,
  LockStockRequest_FieldNumber_Pid = 2,
  LockStockRequest_FieldNumber_SkuId = 3,
  LockStockRequest_FieldNumber_Count = 4,
  LockStockRequest_FieldNumber_URL = 5,
};

@interface LockStockRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseRequest *baseRequest;
/** Test to see if @c baseRequest has been set. */
@property(nonatomic, readwrite) BOOL hasBaseRequest;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pid;
/** Test to see if @c pid has been set. */
@property(nonatomic, readwrite) BOOL hasPid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *skuId;
/** Test to see if @c skuId has been set. */
@property(nonatomic, readwrite) BOOL hasSkuId;

@property(nonatomic, readwrite) uint32_t count;

@property(nonatomic, readwrite) BOOL hasCount;
@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;
/** Test to see if @c URL has been set. */
@property(nonatomic, readwrite) BOOL hasURL;

@end

#pragma mark - LockStockResponse

typedef GPB_ENUM(LockStockResponse_FieldNumber) {
  LockStockResponse_FieldNumber_BaseResponse = 1,
  LockStockResponse_FieldNumber_LockId = 2,
};

@interface LockStockResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@property(nonatomic, readwrite) uint32_t lockId;

@property(nonatomic, readwrite) BOOL hasLockId;
@end

#pragma mark - UnlockStockRequest

typedef GPB_ENUM(UnlockStockRequest_FieldNumber) {
  UnlockStockRequest_FieldNumber_BaseRequest = 1,
  UnlockStockRequest_FieldNumber_Pid = 2,
  UnlockStockRequest_FieldNumber_SkuId = 3,
  UnlockStockRequest_FieldNumber_Count = 4,
  UnlockStockRequest_FieldNumber_URL = 5,
};

@interface UnlockStockRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseRequest *baseRequest;
/** Test to see if @c baseRequest has been set. */
@property(nonatomic, readwrite) BOOL hasBaseRequest;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pid;
/** Test to see if @c pid has been set. */
@property(nonatomic, readwrite) BOOL hasPid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *skuId;
/** Test to see if @c skuId has been set. */
@property(nonatomic, readwrite) BOOL hasSkuId;

@property(nonatomic, readwrite) uint32_t count;

@property(nonatomic, readwrite) BOOL hasCount;
@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;
/** Test to see if @c URL has been set. */
@property(nonatomic, readwrite) BOOL hasURL;

@end

#pragma mark - UnlockStockResponse

typedef GPB_ENUM(UnlockStockResponse_FieldNumber) {
  UnlockStockResponse_FieldNumber_BaseResponse = 1,
  UnlockStockResponse_FieldNumber_LockId = 2,
};

@interface UnlockStockResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@property(nonatomic, readwrite) uint32_t lockId;

@property(nonatomic, readwrite) BOOL hasLockId;
@end

#pragma mark - KVItem

typedef GPB_ENUM(KVItem_FieldNumber) {
  KVItem_FieldNumber_Key = 1,
  KVItem_FieldNumber_Value = 2,
};

@interface KVItem : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *key;
/** Test to see if @c key has been set. */
@property(nonatomic, readwrite) BOOL hasKey;

@property(nonatomic, readwrite, copy, null_resettable) NSString *value;
/** Test to see if @c value has been set. */
@property(nonatomic, readwrite) BOOL hasValue;

@end

#pragma mark - Express

typedef GPB_ENUM(Express_FieldNumber) {
  Express_FieldNumber_Name = 1,
  Express_FieldNumber_Price = 2,
  Express_FieldNumber_PriceType = 3,
  Express_FieldNumber_Id_p = 4,
};

@interface Express : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

@property(nonatomic, readwrite) uint32_t price;

@property(nonatomic, readwrite) BOOL hasPrice;
@property(nonatomic, readwrite, copy, null_resettable) NSString *priceType;
/** Test to see if @c priceType has been set. */
@property(nonatomic, readwrite) BOOL hasPriceType;

@property(nonatomic, readwrite) uint32_t id_p;

@property(nonatomic, readwrite) BOOL hasId_p;
@end

#pragma mark - Address

typedef GPB_ENUM(Address_FieldNumber) {
  Address_FieldNumber_Country = 1,
  Address_FieldNumber_Province = 2,
  Address_FieldNumber_City = 3,
  Address_FieldNumber_Detail = 4,
  Address_FieldNumber_UserName = 5,
  Address_FieldNumber_Tel = 6,
  Address_FieldNumber_ZipCode = 7,
};

@interface Address : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *country;
/** Test to see if @c country has been set. */
@property(nonatomic, readwrite) BOOL hasCountry;

@property(nonatomic, readwrite, copy, null_resettable) NSString *province;
/** Test to see if @c province has been set. */
@property(nonatomic, readwrite) BOOL hasProvince;

@property(nonatomic, readwrite, copy, null_resettable) NSString *city;
/** Test to see if @c city has been set. */
@property(nonatomic, readwrite) BOOL hasCity;

@property(nonatomic, readwrite, copy, null_resettable) NSString *detail;
/** Test to see if @c detail has been set. */
@property(nonatomic, readwrite) BOOL hasDetail;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;
/** Test to see if @c userName has been set. */
@property(nonatomic, readwrite) BOOL hasUserName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tel;
/** Test to see if @c tel has been set. */
@property(nonatomic, readwrite) BOOL hasTel;

@property(nonatomic, readwrite, copy, null_resettable) NSString *zipCode;
/** Test to see if @c zipCode has been set. */
@property(nonatomic, readwrite) BOOL hasZipCode;

@end

#pragma mark - Receipt

typedef GPB_ENUM(Receipt_FieldNumber) {
  Receipt_FieldNumber_IsNeed = 1,
  Receipt_FieldNumber_Detail = 2,
};

@interface Receipt : GPBMessage

@property(nonatomic, readwrite) uint32_t isNeed;

@property(nonatomic, readwrite) BOOL hasIsNeed;
@property(nonatomic, readwrite, copy, null_resettable) NSString *detail;
/** Test to see if @c detail has been set. */
@property(nonatomic, readwrite) BOOL hasDetail;

@end

#pragma mark - Discount

typedef GPB_ENUM(Discount_FieldNumber) {
  Discount_FieldNumber_Title = 1,
  Discount_FieldNumber_Price = 2,
};

@interface Discount : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;
/** Test to see if @c title has been set. */
@property(nonatomic, readwrite) BOOL hasTitle;

@property(nonatomic, readwrite) uint32_t price;

@property(nonatomic, readwrite) BOOL hasPrice;
@end

#pragma mark - Production

typedef GPB_ENUM(Production_FieldNumber) {
  Production_FieldNumber_SkuCount = 1,
  Production_FieldNumber_SkusArray = 2,
  Production_FieldNumber_Count = 3,
  Production_FieldNumber_RealPrice = 4,
  Production_FieldNumber_PriceType = 5,
  Production_FieldNumber_Pid = 6,
  Production_FieldNumber_SafeURL = 7,
  Production_FieldNumber_SkuId = 8,
  Production_FieldNumber_Type = 9,
  Production_FieldNumber_Name = 10,
  Production_FieldNumber_ThumbURL = 11,
  Production_FieldNumber_SubType = 12,
  Production_FieldNumber_Scene = 13,
  Production_FieldNumber_PreferentialPrice = 14,
  Production_FieldNumber_DiscountCount = 15,
  Production_FieldNumber_DiscountsArray = 16,
};

@interface Production : GPBMessage

@property(nonatomic, readwrite) uint32_t skuCount;

@property(nonatomic, readwrite) BOOL hasSkuCount;
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<KVItem*> *skusArray;
/** The number of items in @c skusArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger skusArray_Count;

@property(nonatomic, readwrite) uint32_t count;

@property(nonatomic, readwrite) BOOL hasCount;
@property(nonatomic, readwrite) uint32_t realPrice;

@property(nonatomic, readwrite) BOOL hasRealPrice;
@property(nonatomic, readwrite, copy, null_resettable) NSString *priceType;
/** Test to see if @c priceType has been set. */
@property(nonatomic, readwrite) BOOL hasPriceType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pid;
/** Test to see if @c pid has been set. */
@property(nonatomic, readwrite) BOOL hasPid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *safeURL;
/** Test to see if @c safeURL has been set. */
@property(nonatomic, readwrite) BOOL hasSafeURL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *skuId;
/** Test to see if @c skuId has been set. */
@property(nonatomic, readwrite) BOOL hasSkuId;

@property(nonatomic, readwrite) uint32_t type;

@property(nonatomic, readwrite) BOOL hasType;
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *thumbURL;
/** Test to see if @c thumbURL has been set. */
@property(nonatomic, readwrite) BOOL hasThumbURL;

@property(nonatomic, readwrite) uint32_t subType;

@property(nonatomic, readwrite) BOOL hasSubType;
@property(nonatomic, readwrite) uint32_t scene;

@property(nonatomic, readwrite) BOOL hasScene;
@property(nonatomic, readwrite, copy, null_resettable) NSString *preferentialPrice;
/** Test to see if @c preferentialPrice has been set. */
@property(nonatomic, readwrite) BOOL hasPreferentialPrice;

@property(nonatomic, readwrite) uint32_t discountCount;

@property(nonatomic, readwrite) BOOL hasDiscountCount;
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Discount*> *discountsArray;
/** The number of items in @c discountsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger discountsArray_Count;

@end

#pragma mark - Snapshot

typedef GPB_ENUM(Snapshot_FieldNumber) {
  Snapshot_FieldNumber_ProductCount = 1,
  Snapshot_FieldNumber_ProductionsArray = 2,
  Snapshot_FieldNumber_Express = 3,
  Snapshot_FieldNumber_Address = 4,
  Snapshot_FieldNumber_ReceiptArray = 5,
  Snapshot_FieldNumber_ReceiptCount = 6,
  Snapshot_FieldNumber_LockId = 7,
};

@interface Snapshot : GPBMessage

@property(nonatomic, readwrite) uint32_t productCount;

@property(nonatomic, readwrite) BOOL hasProductCount;
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Production*> *productionsArray;
/** The number of items in @c productionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger productionsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) Express *express;
/** Test to see if @c express has been set. */
@property(nonatomic, readwrite) BOOL hasExpress;

@property(nonatomic, readwrite, strong, null_resettable) Address *address;
/** Test to see if @c address has been set. */
@property(nonatomic, readwrite) BOOL hasAddress;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Receipt*> *receiptArray;
/** The number of items in @c receiptArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger receiptArray_Count;

@property(nonatomic, readwrite) uint32_t receiptCount;

@property(nonatomic, readwrite) BOOL hasReceiptCount;
@property(nonatomic, readwrite, copy, null_resettable) NSString *lockId;
/** Test to see if @c lockId has been set. */
@property(nonatomic, readwrite) BOOL hasLockId;

@end

#pragma mark - SubmitMallOrderRequest

typedef GPB_ENUM(SubmitMallOrderRequest_FieldNumber) {
  SubmitMallOrderRequest_FieldNumber_BaseRequest = 1,
  SubmitMallOrderRequest_FieldNumber_Snapshot = 2,
  SubmitMallOrderRequest_FieldNumber_PayAppid = 3,
};

@interface SubmitMallOrderRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseRequest *baseRequest;
/** Test to see if @c baseRequest has been set. */
@property(nonatomic, readwrite) BOOL hasBaseRequest;

@property(nonatomic, readwrite, strong, null_resettable) Snapshot *snapshot;
/** Test to see if @c snapshot has been set. */
@property(nonatomic, readwrite) BOOL hasSnapshot;

@property(nonatomic, readwrite, copy, null_resettable) NSString *payAppid;
/** Test to see if @c payAppid has been set. */
@property(nonatomic, readwrite) BOOL hasPayAppid;

@end

#pragma mark - SubmitMallOrderResponse

typedef GPB_ENUM(SubmitMallOrderResponse_FieldNumber) {
  SubmitMallOrderResponse_FieldNumber_BaseResponse = 1,
  SubmitMallOrderResponse_FieldNumber_PrepareId = 2,
  SubmitMallOrderResponse_FieldNumber_RetCode = 3,
  SubmitMallOrderResponse_FieldNumber_RetMsg = 4,
};

@interface SubmitMallOrderResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@property(nonatomic, readwrite, copy, null_resettable) NSString *prepareId;
/** Test to see if @c prepareId has been set. */
@property(nonatomic, readwrite) BOOL hasPrepareId;

@property(nonatomic, readwrite) int32_t retCode;

@property(nonatomic, readwrite) BOOL hasRetCode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retMsg;
/** Test to see if @c retMsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetMsg;

@end

#pragma mark - SubmitMallFreeOrderRequest

typedef GPB_ENUM(SubmitMallFreeOrderRequest_FieldNumber) {
  SubmitMallFreeOrderRequest_FieldNumber_BaseRequest = 1,
  SubmitMallFreeOrderRequest_FieldNumber_Snapshot = 2,
};

@interface SubmitMallFreeOrderRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseRequest *baseRequest;
/** Test to see if @c baseRequest has been set. */
@property(nonatomic, readwrite) BOOL hasBaseRequest;

@property(nonatomic, readwrite, strong, null_resettable) Snapshot *snapshot;
/** Test to see if @c snapshot has been set. */
@property(nonatomic, readwrite) BOOL hasSnapshot;

@end

#pragma mark - SubmitMallFreeOrderResponse

typedef GPB_ENUM(SubmitMallFreeOrderResponse_FieldNumber) {
  SubmitMallFreeOrderResponse_FieldNumber_BaseResponse = 1,
  SubmitMallFreeOrderResponse_FieldNumber_PrepareId = 2,
  SubmitMallFreeOrderResponse_FieldNumber_RetCode = 3,
  SubmitMallFreeOrderResponse_FieldNumber_RetMsg = 4,
};

@interface SubmitMallFreeOrderResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@property(nonatomic, readwrite, copy, null_resettable) NSString *prepareId;
/** Test to see if @c prepareId has been set. */
@property(nonatomic, readwrite) BOOL hasPrepareId;

@property(nonatomic, readwrite) int32_t retCode;

@property(nonatomic, readwrite) BOOL hasRetCode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retMsg;
/** Test to see if @c retMsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetMsg;

@end

#pragma mark - SampleProduct

typedef GPB_ENUM(SampleProduct_FieldNumber) {
  SampleProduct_FieldNumber_Pid = 1,
  SampleProduct_FieldNumber_SkuId = 2,
  SampleProduct_FieldNumber_Count = 3,
  SampleProduct_FieldNumber_SafeURL = 4,
};

@interface SampleProduct : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *pid;
/** Test to see if @c pid has been set. */
@property(nonatomic, readwrite) BOOL hasPid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *skuId;
/** Test to see if @c skuId has been set. */
@property(nonatomic, readwrite) BOOL hasSkuId;

@property(nonatomic, readwrite) uint32_t count;

@property(nonatomic, readwrite) BOOL hasCount;
@property(nonatomic, readwrite, copy, null_resettable) NSString *safeURL;
/** Test to see if @c safeURL has been set. */
@property(nonatomic, readwrite) BOOL hasSafeURL;

@end

#pragma mark - ActionAttr

typedef GPB_ENUM(ActionAttr_FieldNumber) {
  ActionAttr_FieldNumber_Name = 1,
  ActionAttr_FieldNumber_Tips = 2,
  ActionAttr_FieldNumber_Type = 3,
  ActionAttr_FieldNumber_Content = 4,
  ActionAttr_FieldNumber_IconURL = 5,
};

@interface ActionAttr : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tips;
/** Test to see if @c tips has been set. */
@property(nonatomic, readwrite) BOOL hasTips;

@property(nonatomic, readwrite) uint32_t type;

@property(nonatomic, readwrite) BOOL hasType;
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;
/** Test to see if @c content has been set. */
@property(nonatomic, readwrite) BOOL hasContent;

@property(nonatomic, readwrite, copy, null_resettable) NSString *iconURL;
/** Test to see if @c iconURL has been set. */
@property(nonatomic, readwrite) BOOL hasIconURL;

@end

#pragma mark - PreSubmitOrderRequest

typedef GPB_ENUM(PreSubmitOrderRequest_FieldNumber) {
  PreSubmitOrderRequest_FieldNumber_BaseRequest = 1,
  PreSubmitOrderRequest_FieldNumber_ProductCount = 2,
  PreSubmitOrderRequest_FieldNumber_ProductArray = 3,
};

@interface PreSubmitOrderRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseRequest *baseRequest;
/** Test to see if @c baseRequest has been set. */
@property(nonatomic, readwrite) BOOL hasBaseRequest;

@property(nonatomic, readwrite) uint32_t productCount;

@property(nonatomic, readwrite) BOOL hasProductCount;
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SampleProduct*> *productArray;
/** The number of items in @c productArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger productArray_Count;

@end

#pragma mark - PreSubmitOrderResponse

typedef GPB_ENUM(PreSubmitOrderResponse_FieldNumber) {
  PreSubmitOrderResponse_FieldNumber_BaseResponse = 1,
  PreSubmitOrderResponse_FieldNumber_ExpressCount = 2,
  PreSubmitOrderResponse_FieldNumber_ExpressArray = 3,
  PreSubmitOrderResponse_FieldNumber_LockId = 4,
  PreSubmitOrderResponse_FieldNumber_RetCode = 5,
  PreSubmitOrderResponse_FieldNumber_RetMsg = 6,
  PreSubmitOrderResponse_FieldNumber_ActionAttrsArray = 7,
  PreSubmitOrderResponse_FieldNumber_ActionAttrCount = 8,
};

@interface PreSubmitOrderResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@property(nonatomic, readwrite) uint32_t expressCount;

@property(nonatomic, readwrite) BOOL hasExpressCount;
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Express*> *expressArray;
/** The number of items in @c expressArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger expressArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *lockId;
/** Test to see if @c lockId has been set. */
@property(nonatomic, readwrite) BOOL hasLockId;

@property(nonatomic, readwrite) int32_t retCode;

@property(nonatomic, readwrite) BOOL hasRetCode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retMsg;
/** Test to see if @c retMsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetMsg;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ActionAttr*> *actionAttrsArray;
/** The number of items in @c actionAttrsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger actionAttrsArray_Count;

@property(nonatomic, readwrite) uint32_t actionAttrCount;

@property(nonatomic, readwrite) BOOL hasActionAttrCount;
@end

#pragma mark - CancelPreOrderRequest

typedef GPB_ENUM(CancelPreOrderRequest_FieldNumber) {
  CancelPreOrderRequest_FieldNumber_BaseRequest = 1,
  CancelPreOrderRequest_FieldNumber_ProductCount = 2,
  CancelPreOrderRequest_FieldNumber_ProductArray = 3,
  CancelPreOrderRequest_FieldNumber_LockId = 4,
};

@interface CancelPreOrderRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseRequest *baseRequest;
/** Test to see if @c baseRequest has been set. */
@property(nonatomic, readwrite) BOOL hasBaseRequest;

@property(nonatomic, readwrite) uint32_t productCount;

@property(nonatomic, readwrite) BOOL hasProductCount;
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SampleProduct*> *productArray;
/** The number of items in @c productArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger productArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *lockId;
/** Test to see if @c lockId has been set. */
@property(nonatomic, readwrite) BOOL hasLockId;

@end

#pragma mark - CancelPreOrderResponse

typedef GPB_ENUM(CancelPreOrderResponse_FieldNumber) {
  CancelPreOrderResponse_FieldNumber_BaseResponse = 1,
  CancelPreOrderResponse_FieldNumber_RetCode = 2,
  CancelPreOrderResponse_FieldNumber_RetMsg = 3,
};

@interface CancelPreOrderResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@property(nonatomic, readwrite) int32_t retCode;

@property(nonatomic, readwrite) BOOL hasRetCode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retMsg;
/** Test to see if @c retMsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetMsg;

@end

#pragma mark - OrderDetailControlRequest

typedef GPB_ENUM(OrderDetailControlRequest_FieldNumber) {
  OrderDetailControlRequest_FieldNumber_BaseRequest = 1,
  OrderDetailControlRequest_FieldNumber_ActionCode = 2,
  OrderDetailControlRequest_FieldNumber_TransId = 3,
};

@interface OrderDetailControlRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseRequest *baseRequest;
/** Test to see if @c baseRequest has been set. */
@property(nonatomic, readwrite) BOOL hasBaseRequest;

@property(nonatomic, readwrite) uint32_t actionCode;

@property(nonatomic, readwrite) BOOL hasActionCode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *transId;
/** Test to see if @c transId has been set. */
@property(nonatomic, readwrite) BOOL hasTransId;

@end

#pragma mark - OrderDetailControlResponse

typedef GPB_ENUM(OrderDetailControlResponse_FieldNumber) {
  OrderDetailControlResponse_FieldNumber_BaseResponse = 1,
  OrderDetailControlResponse_FieldNumber_RetCode = 2,
  OrderDetailControlResponse_FieldNumber_RetMsg = 3,
};

@interface OrderDetailControlResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@property(nonatomic, readwrite) int32_t retCode;

@property(nonatomic, readwrite) BOOL hasRetCode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retMsg;
/** Test to see if @c retMsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetMsg;

@end

#pragma mark - GetProductDiscountRequest

typedef GPB_ENUM(GetProductDiscountRequest_FieldNumber) {
  GetProductDiscountRequest_FieldNumber_BaseRequest = 1,
  GetProductDiscountRequest_FieldNumber_LockId = 2,
  GetProductDiscountRequest_FieldNumber_URL = 3,
};

@interface GetProductDiscountRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseRequest *baseRequest;
/** Test to see if @c baseRequest has been set. */
@property(nonatomic, readwrite) BOOL hasBaseRequest;

@property(nonatomic, readwrite, copy, null_resettable) NSString *lockId;
/** Test to see if @c lockId has been set. */
@property(nonatomic, readwrite) BOOL hasLockId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;
/** Test to see if @c URL has been set. */
@property(nonatomic, readwrite) BOOL hasURL;

@end

#pragma mark - GetProductDiscountResponse

typedef GPB_ENUM(GetProductDiscountResponse_FieldNumber) {
  GetProductDiscountResponse_FieldNumber_BaseResponse = 1,
  GetProductDiscountResponse_FieldNumber_DiscountDetail = 2,
  GetProductDiscountResponse_FieldNumber_RetCode = 3,
  GetProductDiscountResponse_FieldNumber_RetMsg = 4,
};

@interface GetProductDiscountResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@property(nonatomic, readwrite, copy, null_resettable) NSString *discountDetail;
/** Test to see if @c discountDetail has been set. */
@property(nonatomic, readwrite) BOOL hasDiscountDetail;

@property(nonatomic, readwrite) int32_t retCode;

@property(nonatomic, readwrite) BOOL hasRetCode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retMsg;
/** Test to see if @c retMsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetMsg;

@end

#pragma mark - GetLastestExpressInfoRequest

typedef GPB_ENUM(GetLastestExpressInfoRequest_FieldNumber) {
  GetLastestExpressInfoRequest_FieldNumber_BaseRequest = 1,
  GetLastestExpressInfoRequest_FieldNumber_ProductId = 2,
  GetLastestExpressInfoRequest_FieldNumber_LockId = 3,
  GetLastestExpressInfoRequest_FieldNumber_Address = 4,
};

@interface GetLastestExpressInfoRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseRequest *baseRequest;
/** Test to see if @c baseRequest has been set. */
@property(nonatomic, readwrite) BOOL hasBaseRequest;

@property(nonatomic, readwrite, copy, null_resettable) NSString *productId;
/** Test to see if @c productId has been set. */
@property(nonatomic, readwrite) BOOL hasProductId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *lockId;
/** Test to see if @c lockId has been set. */
@property(nonatomic, readwrite) BOOL hasLockId;

@property(nonatomic, readwrite, strong, null_resettable) Address *address;
/** Test to see if @c address has been set. */
@property(nonatomic, readwrite) BOOL hasAddress;

@end

#pragma mark - GetLastestExpressInfoResponse

typedef GPB_ENUM(GetLastestExpressInfoResponse_FieldNumber) {
  GetLastestExpressInfoResponse_FieldNumber_BaseResponse = 1,
  GetLastestExpressInfoResponse_FieldNumber_ExpressListArray = 2,
  GetLastestExpressInfoResponse_FieldNumber_ExpressCount = 3,
  GetLastestExpressInfoResponse_FieldNumber_RetCode = 4,
  GetLastestExpressInfoResponse_FieldNumber_RetMsg = 5,
};

@interface GetLastestExpressInfoResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Express*> *expressListArray;
/** The number of items in @c expressListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger expressListArray_Count;

@property(nonatomic, readwrite) uint32_t expressCount;

@property(nonatomic, readwrite) BOOL hasExpressCount;
@property(nonatomic, readwrite) int32_t retCode;

@property(nonatomic, readwrite) BOOL hasRetCode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retMsg;
/** Test to see if @c retMsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetMsg;

@end

#pragma mark - SendC2CSecMsgRequest

typedef GPB_ENUM(SendC2CSecMsgRequest_FieldNumber) {
  SendC2CSecMsgRequest_FieldNumber_BaseRequest = 1,
  SendC2CSecMsgRequest_FieldNumber_ToUser = 2,
  SendC2CSecMsgRequest_FieldNumber_MsgType = 3,
  SendC2CSecMsgRequest_FieldNumber_TempId = 4,
  SendC2CSecMsgRequest_FieldNumber_Title = 5,
  SendC2CSecMsgRequest_FieldNumber_Des = 6,
  SendC2CSecMsgRequest_FieldNumber_URL = 7,
  SendC2CSecMsgRequest_FieldNumber_Scene = 8,
};

@interface SendC2CSecMsgRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseRequest *baseRequest;
/** Test to see if @c baseRequest has been set. */
@property(nonatomic, readwrite) BOOL hasBaseRequest;

@property(nonatomic, readwrite, copy, null_resettable) NSString *toUser;
/** Test to see if @c toUser has been set. */
@property(nonatomic, readwrite) BOOL hasToUser;

@property(nonatomic, readwrite) int32_t msgType;

@property(nonatomic, readwrite) BOOL hasMsgType;
@property(nonatomic, readwrite, copy, null_resettable) NSString *tempId;
/** Test to see if @c tempId has been set. */
@property(nonatomic, readwrite) BOOL hasTempId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;
/** Test to see if @c title has been set. */
@property(nonatomic, readwrite) BOOL hasTitle;

@property(nonatomic, readwrite, copy, null_resettable) NSString *des;
/** Test to see if @c des has been set. */
@property(nonatomic, readwrite) BOOL hasDes;

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;
/** Test to see if @c URL has been set. */
@property(nonatomic, readwrite) BOOL hasURL;

@property(nonatomic, readwrite) int32_t scene;

@property(nonatomic, readwrite) BOOL hasScene;
@end

#pragma mark - SendC2cSecMsgResponse

typedef GPB_ENUM(SendC2cSecMsgResponse_FieldNumber) {
  SendC2cSecMsgResponse_FieldNumber_BaseResponse = 1,
  SendC2cSecMsgResponse_FieldNumber_ErrCode = 2,
  SendC2cSecMsgResponse_FieldNumber_ErrMsg = 3,
  SendC2cSecMsgResponse_FieldNumber_MsgId = 4,
};

@interface SendC2cSecMsgResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@property(nonatomic, readwrite) int32_t errCode;

@property(nonatomic, readwrite) BOOL hasErrCode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;
/** Test to see if @c errMsg has been set. */
@property(nonatomic, readwrite) BOOL hasErrMsg;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;
/** Test to see if @c msgId has been set. */
@property(nonatomic, readwrite) BOOL hasMsgId;

@end

#pragma mark - GetCardEntranceStyleRequest

typedef GPB_ENUM(GetCardEntranceStyleRequest_FieldNumber) {
  GetCardEntranceStyleRequest_FieldNumber_BaseRequest = 1,
};

@interface GetCardEntranceStyleRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseRequest *baseRequest;
/** Test to see if @c baseRequest has been set. */
@property(nonatomic, readwrite) BOOL hasBaseRequest;

@end

#pragma mark - GetCardEntranceStyleResponse

typedef GPB_ENUM(GetCardEntranceStyleResponse_FieldNumber) {
  GetCardEntranceStyleResponse_FieldNumber_BaseResponse = 1,
  GetCardEntranceStyleResponse_FieldNumber_RetCode = 2,
  GetCardEntranceStyleResponse_FieldNumber_RetMsg = 3,
  GetCardEntranceStyleResponse_FieldNumber_CardHomePageIsNewVersion = 4,
};

@interface GetCardEntranceStyleResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@property(nonatomic, readwrite) uint32_t retCode;

@property(nonatomic, readwrite) BOOL hasRetCode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retMsg;
/** Test to see if @c retMsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetMsg;

@property(nonatomic, readwrite) BOOL cardHomePageIsNewVersion;

@property(nonatomic, readwrite) BOOL hasCardHomePageIsNewVersion;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
