// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wwbiz.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import "Wwbiz.pbobjc.h"
#import "Mmbuiltintype.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - WwbizRoot

@implementation WwbizRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - WwbizRoot_FileDescriptor

static GPBFileDescriptor *WwbizRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"micromsg"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - MMBizCommApiGetServiceAppListReq

@implementation MMBizCommApiGetServiceAppListReq

@dynamic hasBaseRequest, baseRequest;
@dynamic hasOffset, offset;
@dynamic hasLimit, limit;
@dynamic hasLang, lang;
@dynamic hasTpaCountry, tpaCountry;

typedef struct MMBizCommApiGetServiceAppListReq__storage_ {
  uint32_t _has_storage_[1];
  uint32_t offset;
  uint32_t limit;
  BaseRequest *baseRequest;
  NSString *lang;
  NSString *tpaCountry;
} MMBizCommApiGetServiceAppListReq__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "baseRequest",
        .dataTypeSpecific.className = GPBStringifySymbol(BaseRequest),
        .number = MMBizCommApiGetServiceAppListReq_FieldNumber_BaseRequest,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(MMBizCommApiGetServiceAppListReq__storage_, baseRequest),
        .flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "offset",
        .dataTypeSpecific.className = NULL,
        .number = MMBizCommApiGetServiceAppListReq_FieldNumber_Offset,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(MMBizCommApiGetServiceAppListReq__storage_, offset),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "limit",
        .dataTypeSpecific.className = NULL,
        .number = MMBizCommApiGetServiceAppListReq_FieldNumber_Limit,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(MMBizCommApiGetServiceAppListReq__storage_, limit),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "lang",
        .dataTypeSpecific.className = NULL,
        .number = MMBizCommApiGetServiceAppListReq_FieldNumber_Lang,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(MMBizCommApiGetServiceAppListReq__storage_, lang),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "tpaCountry",
        .dataTypeSpecific.className = NULL,
        .number = MMBizCommApiGetServiceAppListReq_FieldNumber_TpaCountry,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(MMBizCommApiGetServiceAppListReq__storage_, tpaCountry),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MMBizCommApiGetServiceAppListReq class]
                                     rootClass:[WwbizRoot class]
                                          file:WwbizRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(MMBizCommApiGetServiceAppListReq__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\005\001K\000\002F\000\003E\000\004D\000\005J\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - MMBizCommApiServiceAppInfo

@implementation MMBizCommApiServiceAppInfo

@dynamic hasAppid, appid;
@dynamic hasAppIconURLPanel, appIconURLPanel;
@dynamic hasAppIconURLList, appIconURLList;
@dynamic hasAppName, appName;
@dynamic hasAppType, appType;
@dynamic hasAppInfoFlag, appInfoFlag;
@dynamic hasAppForwardURL, appForwardURL;
@dynamic hasAppJumpType, appJumpType;
@dynamic hasAppShowFlag, appShowFlag;
@dynamic hasAppShowLang, appShowLang;
@dynamic hasAppUin, appUin;
@dynamic hasAppDisable, appDisable;
@dynamic hasGroupId, groupId;
@dynamic hasRegCountryList, regCountryList;
@dynamic hasAppIconURLPanelOld, appIconURLPanelOld;
@dynamic hasAppIconURLPanelNew, appIconURLPanelNew;
@dynamic hasPrefixCondition, prefixCondition;

typedef struct MMBizCommApiServiceAppInfo__storage_ {
  uint32_t _has_storage_[1];
  uint32_t appType;
  uint32_t appInfoFlag;
  uint32_t appJumpType;
  uint32_t appShowFlag;
  uint32_t appUin;
  uint32_t appDisable;
  uint32_t groupId;
  NSString *appid;
  NSString *appIconURLPanel;
  NSString *appIconURLList;
  NSString *appName;
  NSString *appForwardURL;
  NSString *appShowLang;
  NSString *regCountryList;
  NSString *appIconURLPanelOld;
  NSString *appIconURLPanelNew;
  NSString *prefixCondition;
} MMBizCommApiServiceAppInfo__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "appid",
        .dataTypeSpecific.className = NULL,
        .number = MMBizCommApiServiceAppInfo_FieldNumber_Appid,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(MMBizCommApiServiceAppInfo__storage_, appid),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "appIconURLPanel",
        .dataTypeSpecific.className = NULL,
        .number = MMBizCommApiServiceAppInfo_FieldNumber_AppIconURLPanel,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(MMBizCommApiServiceAppInfo__storage_, appIconURLPanel),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "appIconURLList",
        .dataTypeSpecific.className = NULL,
        .number = MMBizCommApiServiceAppInfo_FieldNumber_AppIconURLList,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(MMBizCommApiServiceAppInfo__storage_, appIconURLList),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "appName",
        .dataTypeSpecific.className = NULL,
        .number = MMBizCommApiServiceAppInfo_FieldNumber_AppName,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(MMBizCommApiServiceAppInfo__storage_, appName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "appType",
        .dataTypeSpecific.className = NULL,
        .number = MMBizCommApiServiceAppInfo_FieldNumber_AppType,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(MMBizCommApiServiceAppInfo__storage_, appType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "appInfoFlag",
        .dataTypeSpecific.className = NULL,
        .number = MMBizCommApiServiceAppInfo_FieldNumber_AppInfoFlag,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(MMBizCommApiServiceAppInfo__storage_, appInfoFlag),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "appForwardURL",
        .dataTypeSpecific.className = NULL,
        .number = MMBizCommApiServiceAppInfo_FieldNumber_AppForwardURL,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(MMBizCommApiServiceAppInfo__storage_, appForwardURL),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "appJumpType",
        .dataTypeSpecific.className = NULL,
        .number = MMBizCommApiServiceAppInfo_FieldNumber_AppJumpType,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(MMBizCommApiServiceAppInfo__storage_, appJumpType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "appShowFlag",
        .dataTypeSpecific.className = NULL,
        .number = MMBizCommApiServiceAppInfo_FieldNumber_AppShowFlag,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(MMBizCommApiServiceAppInfo__storage_, appShowFlag),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "appShowLang",
        .dataTypeSpecific.className = NULL,
        .number = MMBizCommApiServiceAppInfo_FieldNumber_AppShowLang,
        .hasIndex = 9,
        .offset = (uint32_t)offsetof(MMBizCommApiServiceAppInfo__storage_, appShowLang),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "appUin",
        .dataTypeSpecific.className = NULL,
        .number = MMBizCommApiServiceAppInfo_FieldNumber_AppUin,
        .hasIndex = 10,
        .offset = (uint32_t)offsetof(MMBizCommApiServiceAppInfo__storage_, appUin),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "appDisable",
        .dataTypeSpecific.className = NULL,
        .number = MMBizCommApiServiceAppInfo_FieldNumber_AppDisable,
        .hasIndex = 11,
        .offset = (uint32_t)offsetof(MMBizCommApiServiceAppInfo__storage_, appDisable),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "groupId",
        .dataTypeSpecific.className = NULL,
        .number = MMBizCommApiServiceAppInfo_FieldNumber_GroupId,
        .hasIndex = 12,
        .offset = (uint32_t)offsetof(MMBizCommApiServiceAppInfo__storage_, groupId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "regCountryList",
        .dataTypeSpecific.className = NULL,
        .number = MMBizCommApiServiceAppInfo_FieldNumber_RegCountryList,
        .hasIndex = 13,
        .offset = (uint32_t)offsetof(MMBizCommApiServiceAppInfo__storage_, regCountryList),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "appIconURLPanelOld",
        .dataTypeSpecific.className = NULL,
        .number = MMBizCommApiServiceAppInfo_FieldNumber_AppIconURLPanelOld,
        .hasIndex = 14,
        .offset = (uint32_t)offsetof(MMBizCommApiServiceAppInfo__storage_, appIconURLPanelOld),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "appIconURLPanelNew",
        .dataTypeSpecific.className = NULL,
        .number = MMBizCommApiServiceAppInfo_FieldNumber_AppIconURLPanelNew,
        .hasIndex = 15,
        .offset = (uint32_t)offsetof(MMBizCommApiServiceAppInfo__storage_, appIconURLPanelNew),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "prefixCondition",
        .dataTypeSpecific.className = NULL,
        .number = MMBizCommApiServiceAppInfo_FieldNumber_PrefixCondition,
        .hasIndex = 16,
        .offset = (uint32_t)offsetof(MMBizCommApiServiceAppInfo__storage_, prefixCondition),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MMBizCommApiServiceAppInfo class]
                                     rootClass:[WwbizRoot class]
                                          file:WwbizRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(MMBizCommApiServiceAppInfo__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\020\026\010!&\000\027\010!%\000\037\007\000 \007\000!\013\000\"\013!!\000#\013\000$\013\000%\013\000\310\001\006\000\311\001"
        "\n\000\312\001\007\000\313\001\016\000\314\001\010!)\000\315\001\010!)\000\316\001\017\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - MMBizCommApiGetServiceAppListResp

@implementation MMBizCommApiGetServiceAppListResp

@dynamic hasBaseResponse, baseResponse;
@dynamic serviceAppinfoArray, serviceAppinfoArray_Count;

typedef struct MMBizCommApiGetServiceAppListResp__storage_ {
  uint32_t _has_storage_[1];
  BaseResponse *baseResponse;
  NSMutableArray *serviceAppinfoArray;
} MMBizCommApiGetServiceAppListResp__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "baseResponse",
        .dataTypeSpecific.className = GPBStringifySymbol(BaseResponse),
        .number = MMBizCommApiGetServiceAppListResp_FieldNumber_BaseResponse,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(MMBizCommApiGetServiceAppListResp__storage_, baseResponse),
        .flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "serviceAppinfoArray",
        .dataTypeSpecific.className = GPBStringifySymbol(MMBizCommApiServiceAppInfo),
        .number = MMBizCommApiGetServiceAppListResp_FieldNumber_ServiceAppinfoArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(MMBizCommApiGetServiceAppListResp__storage_, serviceAppinfoArray),
        .flags = (GPBFieldFlags)(GPBFieldRepeated | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MMBizCommApiGetServiceAppListResp class]
                                     rootClass:[WwbizRoot class]
                                          file:WwbizRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(MMBizCommApiGetServiceAppListResp__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\001L\000\002\000serviceAppinfo\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
