// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wwbiz.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class BaseRequest;
@class BaseResponse;
@class MMBizCommApiServiceAppInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - WwbizRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface WwbizRoot : GPBRootObject
@end

#pragma mark - MMBizCommApiGetServiceAppListReq

typedef GPB_ENUM(MMBizCommApiGetServiceAppListReq_FieldNumber) {
  MMBizCommApiGetServiceAppListReq_FieldNumber_BaseRequest = 1,
  MMBizCommApiGetServiceAppListReq_FieldNumber_Offset = 2,
  MMBizCommApiGetServiceAppListReq_FieldNumber_Limit = 3,
  MMBizCommApiGetServiceAppListReq_FieldNumber_Lang = 4,
  MMBizCommApiGetServiceAppListReq_FieldNumber_TpaCountry = 5,
};

@interface MMBizCommApiGetServiceAppListReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseRequest *baseRequest;
/** Test to see if @c baseRequest has been set. */
@property(nonatomic, readwrite) BOOL hasBaseRequest;

@property(nonatomic, readwrite) uint32_t offset;

@property(nonatomic, readwrite) BOOL hasOffset;
@property(nonatomic, readwrite) uint32_t limit;

@property(nonatomic, readwrite) BOOL hasLimit;
@property(nonatomic, readwrite, copy, null_resettable) NSString *lang;
/** Test to see if @c lang has been set. */
@property(nonatomic, readwrite) BOOL hasLang;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tpaCountry;
/** Test to see if @c tpaCountry has been set. */
@property(nonatomic, readwrite) BOOL hasTpaCountry;

@end

#pragma mark - MMBizCommApiServiceAppInfo

typedef GPB_ENUM(MMBizCommApiServiceAppInfo_FieldNumber) {
  MMBizCommApiServiceAppInfo_FieldNumber_Appid = 1,
  MMBizCommApiServiceAppInfo_FieldNumber_AppIconURLPanel = 22,
  MMBizCommApiServiceAppInfo_FieldNumber_AppIconURLList = 23,
  MMBizCommApiServiceAppInfo_FieldNumber_AppName = 31,
  MMBizCommApiServiceAppInfo_FieldNumber_AppType = 32,
  MMBizCommApiServiceAppInfo_FieldNumber_AppInfoFlag = 33,
  MMBizCommApiServiceAppInfo_FieldNumber_AppForwardURL = 34,
  MMBizCommApiServiceAppInfo_FieldNumber_AppJumpType = 35,
  MMBizCommApiServiceAppInfo_FieldNumber_AppShowFlag = 36,
  MMBizCommApiServiceAppInfo_FieldNumber_AppShowLang = 37,
  MMBizCommApiServiceAppInfo_FieldNumber_AppUin = 200,
  MMBizCommApiServiceAppInfo_FieldNumber_AppDisable = 201,
  MMBizCommApiServiceAppInfo_FieldNumber_GroupId = 202,
  MMBizCommApiServiceAppInfo_FieldNumber_RegCountryList = 203,
  MMBizCommApiServiceAppInfo_FieldNumber_AppIconURLPanelOld = 204,
  MMBizCommApiServiceAppInfo_FieldNumber_AppIconURLPanelNew = 205,
  MMBizCommApiServiceAppInfo_FieldNumber_PrefixCondition = 206,
};

@interface MMBizCommApiServiceAppInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *appid;
/** Test to see if @c appid has been set. */
@property(nonatomic, readwrite) BOOL hasAppid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appIconURLPanel;
/** Test to see if @c appIconURLPanel has been set. */
@property(nonatomic, readwrite) BOOL hasAppIconURLPanel;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appIconURLList;
/** Test to see if @c appIconURLList has been set. */
@property(nonatomic, readwrite) BOOL hasAppIconURLList;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appName;
/** Test to see if @c appName has been set. */
@property(nonatomic, readwrite) BOOL hasAppName;

@property(nonatomic, readwrite) uint32_t appType;

@property(nonatomic, readwrite) BOOL hasAppType;
@property(nonatomic, readwrite) uint32_t appInfoFlag;

@property(nonatomic, readwrite) BOOL hasAppInfoFlag;
@property(nonatomic, readwrite, copy, null_resettable) NSString *appForwardURL;
/** Test to see if @c appForwardURL has been set. */
@property(nonatomic, readwrite) BOOL hasAppForwardURL;

@property(nonatomic, readwrite) uint32_t appJumpType;

@property(nonatomic, readwrite) BOOL hasAppJumpType;
@property(nonatomic, readwrite) uint32_t appShowFlag;

@property(nonatomic, readwrite) BOOL hasAppShowFlag;
@property(nonatomic, readwrite, copy, null_resettable) NSString *appShowLang;
/** Test to see if @c appShowLang has been set. */
@property(nonatomic, readwrite) BOOL hasAppShowLang;

@property(nonatomic, readwrite) uint32_t appUin;

@property(nonatomic, readwrite) BOOL hasAppUin;
@property(nonatomic, readwrite) uint32_t appDisable;

@property(nonatomic, readwrite) BOOL hasAppDisable;
@property(nonatomic, readwrite) uint32_t groupId;

@property(nonatomic, readwrite) BOOL hasGroupId;
@property(nonatomic, readwrite, copy, null_resettable) NSString *regCountryList;
/** Test to see if @c regCountryList has been set. */
@property(nonatomic, readwrite) BOOL hasRegCountryList;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appIconURLPanelOld;
/** Test to see if @c appIconURLPanelOld has been set. */
@property(nonatomic, readwrite) BOOL hasAppIconURLPanelOld;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appIconURLPanelNew;
/** Test to see if @c appIconURLPanelNew has been set. */
@property(nonatomic, readwrite) BOOL hasAppIconURLPanelNew;

@property(nonatomic, readwrite, copy, null_resettable) NSString *prefixCondition;
/** Test to see if @c prefixCondition has been set. */
@property(nonatomic, readwrite) BOOL hasPrefixCondition;

@end

#pragma mark - MMBizCommApiGetServiceAppListResp

typedef GPB_ENUM(MMBizCommApiGetServiceAppListResp_FieldNumber) {
  MMBizCommApiGetServiceAppListResp_FieldNumber_BaseResponse = 1,
  MMBizCommApiGetServiceAppListResp_FieldNumber_ServiceAppinfoArray = 2,
};

@interface MMBizCommApiGetServiceAppListResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MMBizCommApiServiceAppInfo*> *serviceAppinfoArray;
/** The number of items in @c serviceAppinfoArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger serviceAppinfoArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
