// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mm.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class BaseRequest;
@class BaseResponse;
@class CheckLoginQRCodeResponse_LoginQRCodeNotifyPkg;
@class CheckResUpdateRequest_ResID;
@class CheckResUpdateRequest_ResID_SubTypeVector;
@class ManualAuthAccountRequest;
@class ManualAuthAccountRequest_AesKey;
@class ManualAuthAccountRequest_Ecdh;
@class ManualAuthAccountRequest_Ecdh_EcdhKey;
@class ManualAuthDeviceRequest;
@class ManualAuthDeviceRequest_BaseAuthReqInfo;
@class ManualAuthResponse_AccountInfo;
@class ManualAuthResponse_AuthParam;
@class ManualAuthResponse_AuthParam_Ecdh;
@class ManualAuthResponse_AuthParam_Ecdh_EcdhKey;
@class ManualAuthResponse_AuthParam_SessionKey;
@class ManualAuthResponse_AuthResult;
@class ManualAuthResponse_AuthResult_ErrMsg;
@class ManualAuthResponse_dns_info;
@class ManualAuthResponse_dns_info_ip_info;
@class ManualAuthResponse_dns_info_ip_info_longlink_ip_info;
@class ManualAuthResponse_dns_info_ip_info_shortlink_ip_info;
@class ManualAuthResponse_dns_info_redirect_info;
@class ManualAuthResponse_dns_info_redirect_info_real_host_info;
@class MicroMsgRequestNew;
@class MicroMsgResponseNew;
@class Msg_RawContent;
@class SKBuiltinBuffer_t;
@class SKBuiltinString_t;
@class SnsObject;
@class SnsTimeLineResponse_SnsServerConfig;
@class common_msg;
@class common_msg_Data;
@class contact_info_BeiZhu;
@class contact_info_GroupMemberList;
@class contact_info_GroupMemberList_MemberInfo;
@class contact_info_NickName;
@class contact_info_PY_SHORT;
@class contact_info_QuanPin;
@class contact_info_REAL_PY_SHORT;
@class contact_info_REAL_QuanPin;
@class new_sync_resp_new_msg;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MmRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MmRoot : GPBRootObject
@end

#pragma mark - SKBuiltinBuffer_t

typedef GPB_ENUM(SKBuiltinBuffer_t_FieldNumber) {
  SKBuiltinBuffer_t_FieldNumber_ILen = 1,
  SKBuiltinBuffer_t_FieldNumber_Buffer = 2,
};

@interface SKBuiltinBuffer_t : GPBMessage

@property(nonatomic, readwrite) int32_t iLen;

@property(nonatomic, readwrite) BOOL hasILen;
@property(nonatomic, readwrite, copy, null_resettable) NSData *buffer;
/** Test to see if @c buffer has been set. */
@property(nonatomic, readwrite) BOOL hasBuffer;

@end

#pragma mark - SKBuiltinString_t

typedef GPB_ENUM(SKBuiltinString_t_FieldNumber) {
  SKBuiltinString_t_FieldNumber_String = 1,
};

@interface SKBuiltinString_t : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *string;
/** Test to see if @c string has been set. */
@property(nonatomic, readwrite) BOOL hasString;

@end

#pragma mark - BaseRequest

typedef GPB_ENUM(BaseRequest_FieldNumber) {
  BaseRequest_FieldNumber_SessionKey = 1,
  BaseRequest_FieldNumber_Uin = 2,
  BaseRequest_FieldNumber_DeviceId = 3,
  BaseRequest_FieldNumber_ClientVersion = 4,
  BaseRequest_FieldNumber_DeviceType = 5,
  BaseRequest_FieldNumber_Scene = 6,
};

@interface BaseRequest : GPBMessage

/** 解密服务器返回封包时使用的aeskey */
@property(nonatomic, readwrite, copy, null_resettable) NSData *sessionKey;
/** Test to see if @c sessionKey has been set. */
@property(nonatomic, readwrite) BOOL hasSessionKey;

@property(nonatomic, readwrite) int64_t uin;

@property(nonatomic, readwrite) BOOL hasUin;
/** 手机guid长度16,这里取前15字节,以'\\0'结尾 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *deviceId;
/** Test to see if @c deviceId has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceId;

@property(nonatomic, readwrite) int32_t clientVersion;

@property(nonatomic, readwrite) BOOL hasClientVersion;
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceType;
/** Test to see if @c deviceType has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceType;

@property(nonatomic, readwrite) int32_t scene;

@property(nonatomic, readwrite) BOOL hasScene;
@end

#pragma mark - BaseResponse

typedef GPB_ENUM(BaseResponse_FieldNumber) {
  BaseResponse_FieldNumber_Ret = 1,
  BaseResponse_FieldNumber_ErrMsg = 2,
};

@interface BaseResponse : GPBMessage

/** 错误码 */
@property(nonatomic, readwrite) int32_t ret;

@property(nonatomic, readwrite) BOOL hasRet;
/** 错误信息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;
/** Test to see if @c errMsg has been set. */
@property(nonatomic, readwrite) BOOL hasErrMsg;

@end

#pragma mark - GetLoginQRCodeRequest

typedef GPB_ENUM(GetLoginQRCodeRequest_FieldNumber) {
  GetLoginQRCodeRequest_FieldNumber_BaseRequest = 1,
  GetLoginQRCodeRequest_FieldNumber_RandomEncryKey = 2,
  GetLoginQRCodeRequest_FieldNumber_Opcode = 3,
  GetLoginQRCodeRequest_FieldNumber_DeviceName = 4,
  GetLoginQRCodeRequest_FieldNumber_UserName = 5,
  GetLoginQRCodeRequest_FieldNumber_HardwareExtra = 6,
  GetLoginQRCodeRequest_FieldNumber_SoftType = 7,
  GetLoginQRCodeRequest_FieldNumber_ExtDevLoginType = 8,
  GetLoginQRCodeRequest_FieldNumber_MsgContextPubKey = 9,
};

/**
 * QRCode获取
 **/
@interface GetLoginQRCodeRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseRequest *baseRequest;
/** Test to see if @c baseRequest has been set. */
@property(nonatomic, readwrite) BOOL hasBaseRequest;

/** iPad 16位 iMac 184位 */
@property(nonatomic, readwrite, strong, null_resettable) SKBuiltinBuffer_t *randomEncryKey;
/** Test to see if @c randomEncryKey has been set. */
@property(nonatomic, readwrite) BOOL hasRandomEncryKey;

/** 0 */
@property(nonatomic, readwrite) int32_t opcode;

@property(nonatomic, readwrite) BOOL hasOpcode;
/** iMac "iMac" */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceName;
/** Test to see if @c deviceName has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;
/** Test to see if @c userName has been set. */
@property(nonatomic, readwrite) BOOL hasUserName;

/** iMac 0, */
@property(nonatomic, readwrite) int32_t hardwareExtra;

@property(nonatomic, readwrite) BOOL hasHardwareExtra;
@property(nonatomic, readwrite, copy, null_resettable) NSString *softType;
/** Test to see if @c softType has been set. */
@property(nonatomic, readwrite) BOOL hasSoftType;

/** 0 */
@property(nonatomic, readwrite) int32_t extDevLoginType;

@property(nonatomic, readwrite) BOOL hasExtDevLoginType;
/** iMac */
@property(nonatomic, readwrite, strong, null_resettable) SKBuiltinBuffer_t *msgContextPubKey;
/** Test to see if @c msgContextPubKey has been set. */
@property(nonatomic, readwrite) BOOL hasMsgContextPubKey;

@end

#pragma mark - GetLoginQRCodeResponse

typedef GPB_ENUM(GetLoginQRCodeResponse_FieldNumber) {
  GetLoginQRCodeResponse_FieldNumber_BaseResponse = 1,
  GetLoginQRCodeResponse_FieldNumber_Qrcode = 2,
  GetLoginQRCodeResponse_FieldNumber_Uuid = 3,
  GetLoginQRCodeResponse_FieldNumber_CheckTime = 4,
  GetLoginQRCodeResponse_FieldNumber_NotifyKey = 5,
  GetLoginQRCodeResponse_FieldNumber_ExpiredTime = 6,
  GetLoginQRCodeResponse_FieldNumber_BlueToothBroadCastUuid = 7,
  GetLoginQRCodeResponse_FieldNumber_BlueToothBroadCastContent = 8,
};

@interface GetLoginQRCodeResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@property(nonatomic, readwrite, strong, null_resettable) SKBuiltinBuffer_t *qrcode;
/** Test to see if @c qrcode has been set. */
@property(nonatomic, readwrite) BOOL hasQrcode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;
/** Test to see if @c uuid has been set. */
@property(nonatomic, readwrite) BOOL hasUuid;

@property(nonatomic, readwrite) int32_t checkTime;

@property(nonatomic, readwrite) BOOL hasCheckTime;
@property(nonatomic, readwrite, strong, null_resettable) SKBuiltinBuffer_t *notifyKey;
/** Test to see if @c notifyKey has been set. */
@property(nonatomic, readwrite) BOOL hasNotifyKey;

@property(nonatomic, readwrite) int32_t expiredTime;

@property(nonatomic, readwrite) BOOL hasExpiredTime;
@property(nonatomic, readwrite, copy, null_resettable) NSString *blueToothBroadCastUuid;
/** Test to see if @c blueToothBroadCastUuid has been set. */
@property(nonatomic, readwrite) BOOL hasBlueToothBroadCastUuid;

@property(nonatomic, readwrite, strong, null_resettable) SKBuiltinBuffer_t *blueToothBroadCastContent;
/** Test to see if @c blueToothBroadCastContent has been set. */
@property(nonatomic, readwrite) BOOL hasBlueToothBroadCastContent;

@end

#pragma mark - CheckLoginQRCodeRequest

typedef GPB_ENUM(CheckLoginQRCodeRequest_FieldNumber) {
  CheckLoginQRCodeRequest_FieldNumber_BaseRequest = 1,
  CheckLoginQRCodeRequest_FieldNumber_RandomEncryKey = 2,
  CheckLoginQRCodeRequest_FieldNumber_Uuid = 3,
  CheckLoginQRCodeRequest_FieldNumber_TimeStamp = 4,
  CheckLoginQRCodeRequest_FieldNumber_Opcode = 5,
};

/**
 * QRCode Check
 **/
@interface CheckLoginQRCodeRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseRequest *baseRequest;
/** Test to see if @c baseRequest has been set. */
@property(nonatomic, readwrite) BOOL hasBaseRequest;

@property(nonatomic, readwrite, strong, null_resettable) SKBuiltinBuffer_t *randomEncryKey;
/** Test to see if @c randomEncryKey has been set. */
@property(nonatomic, readwrite) BOOL hasRandomEncryKey;

@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;
/** Test to see if @c uuid has been set. */
@property(nonatomic, readwrite) BOOL hasUuid;

@property(nonatomic, readwrite) int32_t timeStamp;

@property(nonatomic, readwrite) BOOL hasTimeStamp;
@property(nonatomic, readwrite) int32_t opcode;

@property(nonatomic, readwrite) BOOL hasOpcode;
@end

#pragma mark - CheckLoginQRCodeResponse

typedef GPB_ENUM(CheckLoginQRCodeResponse_FieldNumber) {
  CheckLoginQRCodeResponse_FieldNumber_BaseResponse = 1,
  CheckLoginQRCodeResponse_FieldNumber_NotifyPkg = 3,
};

@interface CheckLoginQRCodeResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@property(nonatomic, readwrite, strong, null_resettable) CheckLoginQRCodeResponse_LoginQRCodeNotifyPkg *notifyPkg;
/** Test to see if @c notifyPkg has been set. */
@property(nonatomic, readwrite) BOOL hasNotifyPkg;

@end

#pragma mark - CheckLoginQRCodeResponse_LoginQRCodeNotifyPkg

typedef GPB_ENUM(CheckLoginQRCodeResponse_LoginQRCodeNotifyPkg_FieldNumber) {
  CheckLoginQRCodeResponse_LoginQRCodeNotifyPkg_FieldNumber_NotifyData = 1,
  CheckLoginQRCodeResponse_LoginQRCodeNotifyPkg_FieldNumber_Opcode = 2,
};

@interface CheckLoginQRCodeResponse_LoginQRCodeNotifyPkg : GPBMessage

/** 是bytes,需notifykey不解压aes解密一次,解密后再序列化成下面的对象 */
@property(nonatomic, readwrite, strong, null_resettable) SKBuiltinBuffer_t *notifyData;
/** Test to see if @c notifyData has been set. */
@property(nonatomic, readwrite) BOOL hasNotifyData;

@property(nonatomic, readwrite) int32_t opcode;

@property(nonatomic, readwrite) BOOL hasOpcode;
@end

#pragma mark - NotifyMsg

typedef GPB_ENUM(NotifyMsg_FieldNumber) {
  NotifyMsg_FieldNumber_Uuid = 1,
  NotifyMsg_FieldNumber_State = 2,
  NotifyMsg_FieldNumber_Wxid = 3,
  NotifyMsg_FieldNumber_Wxnewpass = 4,
  NotifyMsg_FieldNumber_Avatar = 5,
  NotifyMsg_FieldNumber_PushLoginURLExpiredTime = 6,
  NotifyMsg_FieldNumber_NickName = 7,
  NotifyMsg_FieldNumber_EffectiveTime = 8,
  NotifyMsg_FieldNumber_T10 = 10,
  NotifyMsg_FieldNumber_Devices = 11,
};

@interface NotifyMsg : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;
/** Test to see if @c uuid has been set. */
@property(nonatomic, readwrite) BOOL hasUuid;

@property(nonatomic, readwrite) int32_t state;

@property(nonatomic, readwrite) BOOL hasState;
@property(nonatomic, readwrite, copy, null_resettable) NSString *wxid;
/** Test to see if @c wxid has been set. */
@property(nonatomic, readwrite) BOOL hasWxid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *wxnewpass;
/** Test to see if @c wxnewpass has been set. */
@property(nonatomic, readwrite) BOOL hasWxnewpass;

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;
/** Test to see if @c avatar has been set. */
@property(nonatomic, readwrite) BOOL hasAvatar;

@property(nonatomic, readwrite) int32_t pushLoginURLExpiredTime;

@property(nonatomic, readwrite) BOOL hasPushLoginURLExpiredTime;
@property(nonatomic, readwrite, copy, null_resettable) NSString *nickName;
/** Test to see if @c nickName has been set. */
@property(nonatomic, readwrite) BOOL hasNickName;

@property(nonatomic, readwrite) int32_t effectiveTime;

@property(nonatomic, readwrite) BOOL hasEffectiveTime;
@property(nonatomic, readwrite) int32_t t10;

@property(nonatomic, readwrite) BOOL hasT10;
@property(nonatomic, readwrite, copy, null_resettable) NSString *devices;
/** Test to see if @c devices has been set. */
@property(nonatomic, readwrite) BOOL hasDevices;

@end

#pragma mark - ManualAuthAccountRequest

typedef GPB_ENUM(ManualAuthAccountRequest_FieldNumber) {
  ManualAuthAccountRequest_FieldNumber_Aes = 1,
  ManualAuthAccountRequest_FieldNumber_Ecdh = 2,
  ManualAuthAccountRequest_FieldNumber_UserName = 3,
  ManualAuthAccountRequest_FieldNumber_Pwd = 4,
  ManualAuthAccountRequest_FieldNumber_Pwd2 = 5,
};

/**
 * 登录请求--账号信息
 **/
@interface ManualAuthAccountRequest : GPBMessage

/** 仅用于本次登录请求,后续通讯使用的aeskey根据服务器返回的数据做ECDH生成 */
@property(nonatomic, readwrite, strong, null_resettable) ManualAuthAccountRequest_AesKey *aes;
/** Test to see if @c aes has been set. */
@property(nonatomic, readwrite) BOOL hasAes;

@property(nonatomic, readwrite, strong, null_resettable) ManualAuthAccountRequest_Ecdh *ecdh;
/** Test to see if @c ecdh has been set. */
@property(nonatomic, readwrite) BOOL hasEcdh;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;
/** Test to see if @c userName has been set. */
@property(nonatomic, readwrite) BOOL hasUserName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pwd;
/** Test to see if @c pwd has been set. */
@property(nonatomic, readwrite) BOOL hasPwd;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pwd2;
/** Test to see if @c pwd2 has been set. */
@property(nonatomic, readwrite) BOOL hasPwd2;

@end

#pragma mark - ManualAuthAccountRequest_AesKey

typedef GPB_ENUM(ManualAuthAccountRequest_AesKey_FieldNumber) {
  ManualAuthAccountRequest_AesKey_FieldNumber_Len = 1,
  ManualAuthAccountRequest_AesKey_FieldNumber_Key = 2,
};

@interface ManualAuthAccountRequest_AesKey : GPBMessage

@property(nonatomic, readwrite) int32_t len;

@property(nonatomic, readwrite) BOOL hasLen;
@property(nonatomic, readwrite, copy, null_resettable) NSData *key;
/** Test to see if @c key has been set. */
@property(nonatomic, readwrite) BOOL hasKey;

@end

#pragma mark - ManualAuthAccountRequest_Ecdh

typedef GPB_ENUM(ManualAuthAccountRequest_Ecdh_FieldNumber) {
  ManualAuthAccountRequest_Ecdh_FieldNumber_Nid = 1,
  ManualAuthAccountRequest_Ecdh_FieldNumber_EcdhKey = 2,
};

@interface ManualAuthAccountRequest_Ecdh : GPBMessage

/** 椭圆曲线类型 */
@property(nonatomic, readwrite) int32_t nid;

@property(nonatomic, readwrite) BOOL hasNid;
@property(nonatomic, readwrite, strong, null_resettable) ManualAuthAccountRequest_Ecdh_EcdhKey *ecdhKey;
/** Test to see if @c ecdhKey has been set. */
@property(nonatomic, readwrite) BOOL hasEcdhKey;

@end

#pragma mark - ManualAuthAccountRequest_Ecdh_EcdhKey

typedef GPB_ENUM(ManualAuthAccountRequest_Ecdh_EcdhKey_FieldNumber) {
  ManualAuthAccountRequest_Ecdh_EcdhKey_FieldNumber_Len = 1,
  ManualAuthAccountRequest_Ecdh_EcdhKey_FieldNumber_Key = 2,
};

@interface ManualAuthAccountRequest_Ecdh_EcdhKey : GPBMessage

@property(nonatomic, readwrite) int32_t len;

@property(nonatomic, readwrite) BOOL hasLen;
/** 椭圆曲线client pubkey */
@property(nonatomic, readwrite, copy, null_resettable) NSData *key;
/** Test to see if @c key has been set. */
@property(nonatomic, readwrite) BOOL hasKey;

@end

#pragma mark - ManualAuthDeviceRequest

typedef GPB_ENUM(ManualAuthDeviceRequest_FieldNumber) {
  ManualAuthDeviceRequest_FieldNumber_BaseRequest = 1,
  ManualAuthDeviceRequest_FieldNumber_BaseReqInfo = 2,
  ManualAuthDeviceRequest_FieldNumber_Imei = 3,
  ManualAuthDeviceRequest_FieldNumber_SoftType = 4,
  ManualAuthDeviceRequest_FieldNumber_BuiltinIpseq = 5,
  ManualAuthDeviceRequest_FieldNumber_ClientSeqId = 6,
  ManualAuthDeviceRequest_FieldNumber_DeviceName = 8,
  ManualAuthDeviceRequest_FieldNumber_DeviceType = 9,
  ManualAuthDeviceRequest_FieldNumber_Language = 10,
  ManualAuthDeviceRequest_FieldNumber_TimeZone = 11,
  ManualAuthDeviceRequest_FieldNumber_Channel = 13,
  ManualAuthDeviceRequest_FieldNumber_TimeStamp = 14,
  ManualAuthDeviceRequest_FieldNumber_DeviceBrand = 15,
  ManualAuthDeviceRequest_FieldNumber_Ostype = 17,
  ManualAuthDeviceRequest_FieldNumber_RealCountry = 18,
  ManualAuthDeviceRequest_FieldNumber_BundleId = 19,
  ManualAuthDeviceRequest_FieldNumber_AdSource = 20,
  ManualAuthDeviceRequest_FieldNumber_IphoneVer = 21,
  ManualAuthDeviceRequest_FieldNumber_InputType = 22,
  ManualAuthDeviceRequest_FieldNumber_ClientCheckData = 23,
};

/**
 * 登录请求--设备信息
 **/
@interface ManualAuthDeviceRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseRequest *baseRequest;
/** Test to see if @c baseRequest has been set. */
@property(nonatomic, readwrite) BOOL hasBaseRequest;

@property(nonatomic, readwrite, strong, null_resettable) ManualAuthDeviceRequest_BaseAuthReqInfo *baseReqInfo;
/** Test to see if @c baseReqInfo has been set. */
@property(nonatomic, readwrite) BOOL hasBaseReqInfo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *imei;
/** Test to see if @c imei has been set. */
@property(nonatomic, readwrite) BOOL hasImei;

/** iPad: <softtype><k3>11.4.1</k3><k9>iPad</k9></softtype> ，iMac不需要此字段 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *softType;
/** Test to see if @c softType has been set. */
@property(nonatomic, readwrite) BOOL hasSoftType;

/** 0 */
@property(nonatomic, readwrite) int32_t builtinIpseq;

@property(nonatomic, readwrite) BOOL hasBuiltinIpseq;
/** iPad: dd09ae95fe48164451be954cd1871cb7-1537165222, iMac: "" */
@property(nonatomic, readwrite, copy, null_resettable) NSString *clientSeqId;
/** Test to see if @c clientSeqId has been set. */
@property(nonatomic, readwrite) BOOL hasClientSeqId;

/** iPad:ccc iPad, iMac: ray的iMac */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceName;
/** Test to see if @c deviceName has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceName;

/** iPad iMac18,2 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceType;
/** Test to see if @c deviceType has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceType;

/** zh_CN */
@property(nonatomic, readwrite, copy, null_resettable) NSString *language;
/** Test to see if @c language has been set. */
@property(nonatomic, readwrite) BOOL hasLanguage;

/** 8.00 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *timeZone;
/** Test to see if @c timeZone has been set. */
@property(nonatomic, readwrite) BOOL hasTimeZone;

/** iPad:3d  iMac:0 */
@property(nonatomic, readwrite) int32_t channel;

@property(nonatomic, readwrite) BOOL hasChannel;
/** 1537178341 */
@property(nonatomic, readwrite) int32_t timeStamp;

@property(nonatomic, readwrite) BOOL hasTimeStamp;
/** Apple */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceBrand;
/** Test to see if @c deviceBrand has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceBrand;

/** iMac "Version 10.13.6 (Build 17G65)" */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ostype;
/** Test to see if @c ostype has been set. */
@property(nonatomic, readwrite) BOOL hasOstype;

/** CN */
@property(nonatomic, readwrite, copy, null_resettable) NSString *realCountry;
/** Test to see if @c realCountry has been set. */
@property(nonatomic, readwrite) BOOL hasRealCountry;

/** iPad:com.tencent.xin , iMac:com.tencent.xinWeChat */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bundleId;
/** Test to see if @c bundleId has been set. */
@property(nonatomic, readwrite) BOOL hasBundleId;

/** iPad:"AAA7AE28-7620-431D-8B4C-7FB4F67AA45E", iMad: "" */
@property(nonatomic, readwrite, copy, null_resettable) NSString *adSource;
/** Test to see if @c adSource has been set. */
@property(nonatomic, readwrite) BOOL hasAdSource;

/** iPad:iPad4,4 , iMac:iMac18,2 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *iphoneVer;
/** Test to see if @c iphoneVer has been set. */
@property(nonatomic, readwrite) BOOL hasIphoneVer;

/** 2 */
@property(nonatomic, readwrite) int32_t inputType;

@property(nonatomic, readwrite) BOOL hasInputType;
@property(nonatomic, readwrite, strong, null_resettable) SKBuiltinBuffer_t *clientCheckData;
/** Test to see if @c clientCheckData has been set. */
@property(nonatomic, readwrite) BOOL hasClientCheckData;

@end

#pragma mark - ManualAuthDeviceRequest_BaseAuthReqInfo

typedef GPB_ENUM(ManualAuthDeviceRequest_BaseAuthReqInfo_FieldNumber) {
  ManualAuthDeviceRequest_BaseAuthReqInfo_FieldNumber_CliDbencryptInfo = 5,
  ManualAuthDeviceRequest_BaseAuthReqInfo_FieldNumber_AuthReqFlag = 7,
};

@interface ManualAuthDeviceRequest_BaseAuthReqInfo : GPBMessage

/** iMac 第一次登陆没有数据，后续登陆会取一个数据。 */
@property(nonatomic, readwrite, strong, null_resettable) SKBuiltinBuffer_t *cliDbencryptInfo;
/** Test to see if @c cliDbencryptInfo has been set. */
@property(nonatomic, readwrite) BOOL hasCliDbencryptInfo;

/** iPad "" iMac 不需要 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *authReqFlag;
/** Test to see if @c authReqFlag has been set. */
@property(nonatomic, readwrite) BOOL hasAuthReqFlag;

@end

#pragma mark - ManualAuthRequest

typedef GPB_ENUM(ManualAuthRequest_FieldNumber) {
  ManualAuthRequest_FieldNumber_RsaReqData = 1,
  ManualAuthRequest_FieldNumber_AesReqData = 2,
};

@interface ManualAuthRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ManualAuthAccountRequest *rsaReqData;
/** Test to see if @c rsaReqData has been set. */
@property(nonatomic, readwrite) BOOL hasRsaReqData;

@property(nonatomic, readwrite, strong, null_resettable) ManualAuthDeviceRequest *aesReqData;
/** Test to see if @c aesReqData has been set. */
@property(nonatomic, readwrite) BOOL hasAesReqData;

@end

#pragma mark - ManualAuthResponse

typedef GPB_ENUM(ManualAuthResponse_FieldNumber) {
  ManualAuthResponse_FieldNumber_Result = 1,
  ManualAuthResponse_FieldNumber_UnifyFlag = 2,
  ManualAuthResponse_FieldNumber_AuthParam = 3,
  ManualAuthResponse_FieldNumber_AccountInfo = 4,
  ManualAuthResponse_FieldNumber_Dns = 5,
};

/**
 * 登录结果
 **/
@interface ManualAuthResponse : GPBMessage

/** 登录结果 */
@property(nonatomic, readwrite, strong, null_resettable) ManualAuthResponse_AuthResult *result;
/** Test to see if @c result has been set. */
@property(nonatomic, readwrite) BOOL hasResult;

@property(nonatomic, readwrite) int32_t unifyFlag;

@property(nonatomic, readwrite) BOOL hasUnifyFlag;
@property(nonatomic, readwrite, strong, null_resettable) ManualAuthResponse_AuthParam *authParam;
/** Test to see if @c authParam has been set. */
@property(nonatomic, readwrite) BOOL hasAuthParam;

/** 登录成功后返回账号信息 */
@property(nonatomic, readwrite, strong, null_resettable) ManualAuthResponse_AccountInfo *accountInfo;
/** Test to see if @c accountInfo has been set. */
@property(nonatomic, readwrite) BOOL hasAccountInfo;

/** dns信息 */
@property(nonatomic, readwrite, strong, null_resettable) ManualAuthResponse_dns_info *dns;
/** Test to see if @c dns has been set. */
@property(nonatomic, readwrite) BOOL hasDns;

@end

#pragma mark - ManualAuthResponse_AuthResult

typedef GPB_ENUM(ManualAuthResponse_AuthResult_FieldNumber) {
  ManualAuthResponse_AuthResult_FieldNumber_Code = 1,
  ManualAuthResponse_AuthResult_FieldNumber_ErrMsg = 2,
};

@interface ManualAuthResponse_AuthResult : GPBMessage

/** 登录错误码 */
@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite) BOOL hasCode;
@property(nonatomic, readwrite, strong, null_resettable) ManualAuthResponse_AuthResult_ErrMsg *errMsg;
/** Test to see if @c errMsg has been set. */
@property(nonatomic, readwrite) BOOL hasErrMsg;

@end

#pragma mark - ManualAuthResponse_AuthResult_ErrMsg

typedef GPB_ENUM(ManualAuthResponse_AuthResult_ErrMsg_FieldNumber) {
  ManualAuthResponse_AuthResult_ErrMsg_FieldNumber_Msg = 1,
};

@interface ManualAuthResponse_AuthResult_ErrMsg : GPBMessage

/** 错误信息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - ManualAuthResponse_AuthParam

typedef GPB_ENUM(ManualAuthResponse_AuthParam_FieldNumber) {
  ManualAuthResponse_AuthParam_FieldNumber_Uin = 1,
  ManualAuthResponse_AuthParam_FieldNumber_Ecdh = 2,
  ManualAuthResponse_AuthParam_FieldNumber_Session = 3,
  ManualAuthResponse_AuthParam_FieldNumber_SmsTicket = 16,
  ManualAuthResponse_AuthParam_FieldNumber_BindMailLoginURL = 20,
  ManualAuthResponse_AuthParam_FieldNumber_ServerTime = 22,
};

@interface ManualAuthResponse_AuthParam : GPBMessage

@property(nonatomic, readwrite) int64_t uin;

@property(nonatomic, readwrite) BOOL hasUin;
@property(nonatomic, readwrite, strong, null_resettable) ManualAuthResponse_AuthParam_Ecdh *ecdh;
/** Test to see if @c ecdh has been set. */
@property(nonatomic, readwrite) BOOL hasEcdh;

/** 加密的sessionKey 需要使用ECDH握手后的密钥做AES解密得到最终长16字节的aeskey */
@property(nonatomic, readwrite, strong, null_resettable) ManualAuthResponse_AuthParam_SessionKey *session;
/** Test to see if @c session has been set. */
@property(nonatomic, readwrite) BOOL hasSession;

/** 需要短信授权时的ticket,用于后续请求验证码以及发送验证码 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *smsTicket;
/** Test to see if @c smsTicket has been set. */
@property(nonatomic, readwrite) BOOL hasSmsTicket;

@property(nonatomic, readwrite, copy, null_resettable) NSString *bindMailLoginURL;
/** Test to see if @c bindMailLoginURL has been set. */
@property(nonatomic, readwrite) BOOL hasBindMailLoginURL;

@property(nonatomic, readwrite) int32_t serverTime;

@property(nonatomic, readwrite) BOOL hasServerTime;
@end

#pragma mark - ManualAuthResponse_AuthParam_Ecdh

typedef GPB_ENUM(ManualAuthResponse_AuthParam_Ecdh_FieldNumber) {
  ManualAuthResponse_AuthParam_Ecdh_FieldNumber_Nid = 1,
  ManualAuthResponse_AuthParam_Ecdh_FieldNumber_EcdhKey = 2,
};

@interface ManualAuthResponse_AuthParam_Ecdh : GPBMessage

@property(nonatomic, readwrite) int32_t nid;

@property(nonatomic, readwrite) BOOL hasNid;
@property(nonatomic, readwrite, strong, null_resettable) ManualAuthResponse_AuthParam_Ecdh_EcdhKey *ecdhKey;
/** Test to see if @c ecdhKey has been set. */
@property(nonatomic, readwrite) BOOL hasEcdhKey;

@end

#pragma mark - ManualAuthResponse_AuthParam_Ecdh_EcdhKey

typedef GPB_ENUM(ManualAuthResponse_AuthParam_Ecdh_EcdhKey_FieldNumber) {
  ManualAuthResponse_AuthParam_Ecdh_EcdhKey_FieldNumber_Len = 1,
  ManualAuthResponse_AuthParam_Ecdh_EcdhKey_FieldNumber_Key = 2,
};

@interface ManualAuthResponse_AuthParam_Ecdh_EcdhKey : GPBMessage

@property(nonatomic, readwrite) int32_t len;

@property(nonatomic, readwrite) BOOL hasLen;
/** 椭圆曲线server pubkey */
@property(nonatomic, readwrite, copy, null_resettable) NSData *key;
/** Test to see if @c key has been set. */
@property(nonatomic, readwrite) BOOL hasKey;

@end

#pragma mark - ManualAuthResponse_AuthParam_SessionKey

typedef GPB_ENUM(ManualAuthResponse_AuthParam_SessionKey_FieldNumber) {
  ManualAuthResponse_AuthParam_SessionKey_FieldNumber_Len = 1,
  ManualAuthResponse_AuthParam_SessionKey_FieldNumber_Key = 2,
};

@interface ManualAuthResponse_AuthParam_SessionKey : GPBMessage

@property(nonatomic, readwrite) int32_t len;

@property(nonatomic, readwrite) BOOL hasLen;
@property(nonatomic, readwrite, copy, null_resettable) NSData *key;
/** Test to see if @c key has been set. */
@property(nonatomic, readwrite) BOOL hasKey;

@end

#pragma mark - ManualAuthResponse_AccountInfo

typedef GPB_ENUM(ManualAuthResponse_AccountInfo_FieldNumber) {
  ManualAuthResponse_AccountInfo_FieldNumber_WxId = 1,
  ManualAuthResponse_AccountInfo_FieldNumber_NickName = 2,
  ManualAuthResponse_AccountInfo_FieldNumber_Tag3 = 3,
  ManualAuthResponse_AccountInfo_FieldNumber_BindMail = 4,
  ManualAuthResponse_AccountInfo_FieldNumber_BindMobile = 5,
  ManualAuthResponse_AccountInfo_FieldNumber_Alias = 6,
  ManualAuthResponse_AccountInfo_FieldNumber_Tag7 = 7,
  ManualAuthResponse_AccountInfo_FieldNumber_Status = 8,
  ManualAuthResponse_AccountInfo_FieldNumber_PluginFlag = 9,
  ManualAuthResponse_AccountInfo_FieldNumber_RegisterType = 10,
  ManualAuthResponse_AccountInfo_FieldNumber_Tag11 = 11,
  ManualAuthResponse_AccountInfo_FieldNumber_SafeDevice = 12,
  ManualAuthResponse_AccountInfo_FieldNumber_OfficialNamePinyin = 13,
  ManualAuthResponse_AccountInfo_FieldNumber_OfficialNameZh = 14,
  ManualAuthResponse_AccountInfo_FieldNumber_Tag15 = 15,
  ManualAuthResponse_AccountInfo_FieldNumber_FsURL = 16,
};

@interface ManualAuthResponse_AccountInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *wxId;
/** Test to see if @c wxId has been set. */
@property(nonatomic, readwrite) BOOL hasWxId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nickName;
/** Test to see if @c nickName has been set. */
@property(nonatomic, readwrite) BOOL hasNickName;

@property(nonatomic, readwrite) int32_t tag3;

@property(nonatomic, readwrite) BOOL hasTag3;
@property(nonatomic, readwrite, copy, null_resettable) NSString *bindMail;
/** Test to see if @c bindMail has been set. */
@property(nonatomic, readwrite) BOOL hasBindMail;

@property(nonatomic, readwrite, copy, null_resettable) NSString *bindMobile;
/** Test to see if @c bindMobile has been set. */
@property(nonatomic, readwrite) BOOL hasBindMobile;

@property(nonatomic, readwrite, copy, null_resettable) NSString *alias;
/** Test to see if @c alias has been set. */
@property(nonatomic, readwrite) BOOL hasAlias;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tag7;
/** Test to see if @c tag7 has been set. */
@property(nonatomic, readwrite) BOOL hasTag7;

@property(nonatomic, readwrite) int32_t status;

@property(nonatomic, readwrite) BOOL hasStatus;
@property(nonatomic, readwrite) int32_t pluginFlag;

@property(nonatomic, readwrite) BOOL hasPluginFlag;
@property(nonatomic, readwrite) int32_t registerType;

@property(nonatomic, readwrite) BOOL hasRegisterType;
@property(nonatomic, readwrite, copy, null_resettable) NSString *tag11;
/** Test to see if @c tag11 has been set. */
@property(nonatomic, readwrite) BOOL hasTag11;

@property(nonatomic, readwrite) int32_t safeDevice;

@property(nonatomic, readwrite) BOOL hasSafeDevice;
@property(nonatomic, readwrite, copy, null_resettable) NSString *officialNamePinyin;
/** Test to see if @c officialNamePinyin has been set. */
@property(nonatomic, readwrite) BOOL hasOfficialNamePinyin;

@property(nonatomic, readwrite, copy, null_resettable) NSString *officialNameZh;
/** Test to see if @c officialNameZh has been set. */
@property(nonatomic, readwrite) BOOL hasOfficialNameZh;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tag15;
/** Test to see if @c tag15 has been set. */
@property(nonatomic, readwrite) BOOL hasTag15;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fsURL;
/** Test to see if @c fsURL has been set. */
@property(nonatomic, readwrite) BOOL hasFsURL;

@end

#pragma mark - ManualAuthResponse_dns_info

typedef GPB_ENUM(ManualAuthResponse_dns_info_FieldNumber) {
  ManualAuthResponse_dns_info_FieldNumber_Redirect = 1,
  ManualAuthResponse_dns_info_FieldNumber_Ip = 3,
};

@interface ManualAuthResponse_dns_info : GPBMessage

/** 域名重定向信息 */
@property(nonatomic, readwrite, strong, null_resettable) ManualAuthResponse_dns_info_redirect_info *redirect;
/** Test to see if @c redirect has been set. */
@property(nonatomic, readwrite) BOOL hasRedirect;

/** 长短链接ip */
@property(nonatomic, readwrite, strong, null_resettable) ManualAuthResponse_dns_info_ip_info *ip;
/** Test to see if @c ip has been set. */
@property(nonatomic, readwrite) BOOL hasIp;

@end

#pragma mark - ManualAuthResponse_dns_info_redirect_info

typedef GPB_ENUM(ManualAuthResponse_dns_info_redirect_info_FieldNumber) {
  ManualAuthResponse_dns_info_redirect_info_FieldNumber_Cnt = 1,
  ManualAuthResponse_dns_info_redirect_info_FieldNumber_RealHostArray = 2,
};

@interface ManualAuthResponse_dns_info_redirect_info : GPBMessage

/** host cnt */
@property(nonatomic, readwrite) int32_t cnt;

@property(nonatomic, readwrite) BOOL hasCnt;
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ManualAuthResponse_dns_info_redirect_info_real_host_info*> *realHostArray;
/** The number of items in @c realHostArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger realHostArray_Count;

@end

#pragma mark - ManualAuthResponse_dns_info_redirect_info_real_host_info

typedef GPB_ENUM(ManualAuthResponse_dns_info_redirect_info_real_host_info_FieldNumber) {
  ManualAuthResponse_dns_info_redirect_info_real_host_info_FieldNumber_Host = 1,
  ManualAuthResponse_dns_info_redirect_info_real_host_info_FieldNumber_Redirect = 2,
};

@interface ManualAuthResponse_dns_info_redirect_info_real_host_info : GPBMessage

/** host */
@property(nonatomic, readwrite, copy, null_resettable) NSString *host;
/** Test to see if @c host has been set. */
@property(nonatomic, readwrite) BOOL hasHost;

/** redirect_host */
@property(nonatomic, readwrite, copy, null_resettable) NSString *redirect;
/** Test to see if @c redirect has been set. */
@property(nonatomic, readwrite) BOOL hasRedirect;

@end

#pragma mark - ManualAuthResponse_dns_info_ip_info

typedef GPB_ENUM(ManualAuthResponse_dns_info_ip_info_FieldNumber) {
  ManualAuthResponse_dns_info_ip_info_FieldNumber_LonglinkIpCnt = 1,
  ManualAuthResponse_dns_info_ip_info_FieldNumber_ShortlinkIpCnt = 2,
  ManualAuthResponse_dns_info_ip_info_FieldNumber_LonglinkArray = 3,
  ManualAuthResponse_dns_info_ip_info_FieldNumber_ShortlinkArray = 4,
};

@interface ManualAuthResponse_dns_info_ip_info : GPBMessage

/** 长链接ip池数量 */
@property(nonatomic, readwrite) int32_t longlinkIpCnt;

@property(nonatomic, readwrite) BOOL hasLonglinkIpCnt;
/** 短链接ip池数量 */
@property(nonatomic, readwrite) int32_t shortlinkIpCnt;

@property(nonatomic, readwrite) BOOL hasShortlinkIpCnt;
/** 长链接ip池 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ManualAuthResponse_dns_info_ip_info_longlink_ip_info*> *longlinkArray;
/** The number of items in @c longlinkArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger longlinkArray_Count;

/** 短链接ip池 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ManualAuthResponse_dns_info_ip_info_shortlink_ip_info*> *shortlinkArray;
/** The number of items in @c shortlinkArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger shortlinkArray_Count;

@end

#pragma mark - ManualAuthResponse_dns_info_ip_info_longlink_ip_info

typedef GPB_ENUM(ManualAuthResponse_dns_info_ip_info_longlink_ip_info_FieldNumber) {
  ManualAuthResponse_dns_info_ip_info_longlink_ip_info_FieldNumber_Ip = 3,
  ManualAuthResponse_dns_info_ip_info_longlink_ip_info_FieldNumber_Host = 4,
};

@interface ManualAuthResponse_dns_info_ip_info_longlink_ip_info : GPBMessage

/** ip */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ip;
/** Test to see if @c ip has been set. */
@property(nonatomic, readwrite) BOOL hasIp;

/** host */
@property(nonatomic, readwrite, copy, null_resettable) NSString *host;
/** Test to see if @c host has been set. */
@property(nonatomic, readwrite) BOOL hasHost;

@end

#pragma mark - ManualAuthResponse_dns_info_ip_info_shortlink_ip_info

typedef GPB_ENUM(ManualAuthResponse_dns_info_ip_info_shortlink_ip_info_FieldNumber) {
  ManualAuthResponse_dns_info_ip_info_shortlink_ip_info_FieldNumber_Ip = 3,
  ManualAuthResponse_dns_info_ip_info_shortlink_ip_info_FieldNumber_Host = 4,
};

@interface ManualAuthResponse_dns_info_ip_info_shortlink_ip_info : GPBMessage

/** ip */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ip;
/** Test to see if @c ip has been set. */
@property(nonatomic, readwrite) BOOL hasIp;

/** host */
@property(nonatomic, readwrite, copy, null_resettable) NSString *host;
/** Test to see if @c host has been set. */
@property(nonatomic, readwrite) BOOL hasHost;

@end

#pragma mark - NewInitRequest

typedef GPB_ENUM(NewInitRequest_FieldNumber) {
  NewInitRequest_FieldNumber_BaseRequest = 1,
  NewInitRequest_FieldNumber_UserName = 2,
  NewInitRequest_FieldNumber_CurrentSynckey = 3,
  NewInitRequest_FieldNumber_MaxSynckey = 4,
  NewInitRequest_FieldNumber_Language = 5,
};

/**
 * 新设备第一次登录初始化请求
 **/
@interface NewInitRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseRequest *baseRequest;
/** Test to see if @c baseRequest has been set. */
@property(nonatomic, readwrite) BOOL hasBaseRequest;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;
/** Test to see if @c userName has been set. */
@property(nonatomic, readwrite) BOOL hasUserName;

/** 首次初始化时sync_key_cur = '' */
@property(nonatomic, readwrite, copy, null_resettable) NSData *currentSynckey;
/** Test to see if @c currentSynckey has been set. */
@property(nonatomic, readwrite) BOOL hasCurrentSynckey;

/** 首次初始化时sync_key_max = '' */
@property(nonatomic, readwrite, copy, null_resettable) NSData *maxSynckey;
/** Test to see if @c maxSynckey has been set. */
@property(nonatomic, readwrite) BOOL hasMaxSynckey;

@property(nonatomic, readwrite, copy, null_resettable) NSString *language;
/** Test to see if @c language has been set. */
@property(nonatomic, readwrite) BOOL hasLanguage;

@end

#pragma mark - Msg

typedef GPB_ENUM(Msg_FieldNumber) {
  Msg_FieldNumber_Serverid = 1,
  Msg_FieldNumber_FromId = 2,
  Msg_FieldNumber_ToId = 3,
  Msg_FieldNumber_Type = 4,
  Msg_FieldNumber_Raw = 5,
  Msg_FieldNumber_Status = 6,
  Msg_FieldNumber_Tag7 = 7,
  Msg_FieldNumber_Tag8 = 8,
  Msg_FieldNumber_CreateTime = 9,
  Msg_FieldNumber_ExInfo = 10,
  Msg_FieldNumber_XmlContent = 11,
  Msg_FieldNumber_SvrId = 12,
  Msg_FieldNumber_MsgKey = 13,
};

/**
 * 服务器返回消息(newinit/newsync)
 **/
@interface Msg : GPBMessage

@property(nonatomic, readwrite) int64_t serverid;

@property(nonatomic, readwrite) BOOL hasServerid;
/** 发送方wxid */
@property(nonatomic, readwrite, strong, null_resettable) SKBuiltinString_t *fromId;
/** Test to see if @c fromId has been set. */
@property(nonatomic, readwrite) BOOL hasFromId;

/** 接收方wxid */
@property(nonatomic, readwrite, strong, null_resettable) SKBuiltinString_t *toId;
/** Test to see if @c toId has been set. */
@property(nonatomic, readwrite) BOOL hasToId;

/** 消息类型:9999==>系统垃圾消息,10002==>sysmsg(系统垃圾消息),49==>appmsg,1==>文字消息,10000==>系统提示 */
@property(nonatomic, readwrite) int32_t type;

@property(nonatomic, readwrite) BOOL hasType;
/** 原始消息内容,需要根据不同消息类型解析 */
@property(nonatomic, readwrite, strong, null_resettable) Msg_RawContent *raw;
/** Test to see if @c raw has been set. */
@property(nonatomic, readwrite) BOOL hasRaw;

@property(nonatomic, readwrite) int32_t status;

@property(nonatomic, readwrite) BOOL hasStatus;
@property(nonatomic, readwrite) int32_t tag7;

@property(nonatomic, readwrite) BOOL hasTag7;
@property(nonatomic, readwrite, copy, null_resettable) NSData *tag8;
/** Test to see if @c tag8 has been set. */
@property(nonatomic, readwrite) BOOL hasTag8;

/** 消息发送时间 */
@property(nonatomic, readwrite) int32_t createTime;

@property(nonatomic, readwrite) BOOL hasCreateTime;
/** 消息附加内容(群是否屏蔽,群人数,群at功能) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *exInfo;
/** Test to see if @c exInfo has been set. */
@property(nonatomic, readwrite) BOOL hasExInfo;

/** 推送内容(xml格式) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *xmlContent;
/** Test to see if @c xmlContent has been set. */
@property(nonatomic, readwrite) BOOL hasXmlContent;

/** 每条消息的唯一id */
@property(nonatomic, readwrite) int64_t svrId;

@property(nonatomic, readwrite) BOOL hasSvrId;
/** sync key中的id */
@property(nonatomic, readwrite) int32_t msgKey;

@property(nonatomic, readwrite) BOOL hasMsgKey;
@end

#pragma mark - Msg_RawContent

typedef GPB_ENUM(Msg_RawContent_FieldNumber) {
  Msg_RawContent_FieldNumber_Content = 1,
};

@interface Msg_RawContent : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;
/** Test to see if @c content has been set. */
@property(nonatomic, readwrite) BOOL hasContent;

@end

#pragma mark - contact_info

typedef GPB_ENUM(contact_info_FieldNumber) {
  contact_info_FieldNumber_Wxid = 1,
  contact_info_FieldNumber_Nickname = 2,
  contact_info_FieldNumber_ShortPy = 3,
  contact_info_FieldNumber_Quanpin = 4,
  contact_info_FieldNumber_Sex = 5,
  contact_info_FieldNumber_Tag6 = 6,
  contact_info_FieldNumber_Tag7 = 7,
  contact_info_FieldNumber_Type = 8,
  contact_info_FieldNumber_Tag9 = 9,
  contact_info_FieldNumber_RemarkName = 10,
  contact_info_FieldNumber_RealShortPy = 11,
  contact_info_FieldNumber_RealQuanpin = 12,
  contact_info_FieldNumber_Tag13 = 13,
  contact_info_FieldNumber_Tag14 = 14,
  contact_info_FieldNumber_Tag16 = 16,
  contact_info_FieldNumber_BChatRoom = 17,
  contact_info_FieldNumber_Tag18 = 18,
  contact_info_FieldNumber_Sheng = 19,
  contact_info_FieldNumber_Shi = 20,
  contact_info_FieldNumber_Qianming = 21,
  contact_info_FieldNumber_Tag22 = 22,
  contact_info_FieldNumber_Tag23 = 23,
  contact_info_FieldNumber_RegisterBodyType = 24,
  contact_info_FieldNumber_RegisterBody = 25,
  contact_info_FieldNumber_Tag26 = 26,
  contact_info_FieldNumber_Src = 27,
  contact_info_FieldNumber_LastMsgTime = 29,
  contact_info_FieldNumber_Alias = 30,
  contact_info_FieldNumber_ChatroomOwnerWxid = 31,
  contact_info_FieldNumber_Tag33 = 33,
  contact_info_FieldNumber_Tag34 = 34,
  contact_info_FieldNumber_Tag35 = 35,
  contact_info_FieldNumber_Tag37 = 37,
  contact_info_FieldNumber_Country = 38,
  contact_info_FieldNumber_AvatarBig = 39,
  contact_info_FieldNumber_AvatarSmall = 40,
  contact_info_FieldNumber_Tag42 = 42,
  contact_info_FieldNumber_V1Name = 45,
  contact_info_FieldNumber_Tag50 = 50,
  contact_info_FieldNumber_ChatroomServerVer = 53,
  contact_info_FieldNumber_ChatroomMaxMember = 55,
  contact_info_FieldNumber_Tag56 = 56,
  contact_info_FieldNumber_GroupMemberList = 57,
  contact_info_FieldNumber_Tag58 = 58,
  contact_info_FieldNumber_Tag62 = 62,
  contact_info_FieldNumber_Tag64 = 64,
  contact_info_FieldNumber_Tag65 = 65,
  contact_info_FieldNumber_Tag66 = 66,
  contact_info_FieldNumber_Tag67 = 67,
};

/**
 * 好友详细信息
 **/
@interface contact_info : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) SKBuiltinString_t *wxid;
/** Test to see if @c wxid has been set. */
@property(nonatomic, readwrite) BOOL hasWxid;

@property(nonatomic, readwrite, strong, null_resettable) contact_info_NickName *nickname;
/** Test to see if @c nickname has been set. */
@property(nonatomic, readwrite) BOOL hasNickname;

@property(nonatomic, readwrite, strong, null_resettable) contact_info_PY_SHORT *shortPy;
/** Test to see if @c shortPy has been set. */
@property(nonatomic, readwrite) BOOL hasShortPy;

@property(nonatomic, readwrite, strong, null_resettable) contact_info_QuanPin *quanpin;
/** Test to see if @c quanpin has been set. */
@property(nonatomic, readwrite) BOOL hasQuanpin;

/** 性别：0=>未知,1=>男,2=>女 */
@property(nonatomic, readwrite) int32_t sex;

@property(nonatomic, readwrite) BOOL hasSex;
@property(nonatomic, readwrite, copy, null_resettable) NSString *tag6;
/** Test to see if @c tag6 has been set. */
@property(nonatomic, readwrite) BOOL hasTag6;

@property(nonatomic, readwrite) int32_t tag7;

@property(nonatomic, readwrite) BOOL hasTag7;
/** 好友状态: */
@property(nonatomic, readwrite) int32_t type;

@property(nonatomic, readwrite) BOOL hasType;
@property(nonatomic, readwrite) int32_t tag9;

@property(nonatomic, readwrite) BOOL hasTag9;
/** 备注名:为空则显示nickname */
@property(nonatomic, readwrite, strong, null_resettable) contact_info_BeiZhu *remarkName;
/** Test to see if @c remarkName has been set. */
@property(nonatomic, readwrite) BOOL hasRemarkName;

@property(nonatomic, readwrite, strong, null_resettable) contact_info_REAL_PY_SHORT *realShortPy;
/** Test to see if @c realShortPy has been set. */
@property(nonatomic, readwrite) BOOL hasRealShortPy;

@property(nonatomic, readwrite, strong, null_resettable) contact_info_REAL_QuanPin *realQuanpin;
/** Test to see if @c realQuanpin has been set. */
@property(nonatomic, readwrite) BOOL hasRealQuanpin;

@property(nonatomic, readwrite) int32_t tag13;

@property(nonatomic, readwrite) BOOL hasTag13;
@property(nonatomic, readwrite) int32_t tag14;

@property(nonatomic, readwrite) BOOL hasTag14;
@property(nonatomic, readwrite, copy, null_resettable) NSString *tag16;
/** Test to see if @c tag16 has been set. */
@property(nonatomic, readwrite) BOOL hasTag16;

/** todo */
@property(nonatomic, readwrite) int32_t bChatRoom;

@property(nonatomic, readwrite) BOOL hasBChatRoom;
@property(nonatomic, readwrite) int32_t tag18;

@property(nonatomic, readwrite) BOOL hasTag18;
@property(nonatomic, readwrite, copy, null_resettable) NSString *sheng;
/** Test to see if @c sheng has been set. */
@property(nonatomic, readwrite) BOOL hasSheng;

@property(nonatomic, readwrite, copy, null_resettable) NSString *shi;
/** Test to see if @c shi has been set. */
@property(nonatomic, readwrite) BOOL hasShi;

/** 签名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *qianming;
/** Test to see if @c qianming has been set. */
@property(nonatomic, readwrite) BOOL hasQianming;

/** todo */
@property(nonatomic, readwrite) int32_t tag22;

@property(nonatomic, readwrite) BOOL hasTag22;
/** todo */
@property(nonatomic, readwrite) int32_t tag23;

@property(nonatomic, readwrite) BOOL hasTag23;
/** 8=>个人;24=>公司 */
@property(nonatomic, readwrite) int32_t registerBodyType;

@property(nonatomic, readwrite) BOOL hasRegisterBodyType;
/** 注册主体:xx公司或个人 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *registerBody;
/** Test to see if @c registerBody has been set. */
@property(nonatomic, readwrite) BOOL hasRegisterBody;

@property(nonatomic, readwrite) int32_t tag26;

@property(nonatomic, readwrite) BOOL hasTag26;
/** 好友来源:(10000XX为对方添加自己)0=>未知;1=>QQ;3=>微信号;6=>名片;13=>手机通讯录;14=>群聊;15=>手机号;30=>扫一扫  （1000015=>对方手机号;1000030=>对方扫一扫;1000014=>对方群聊......） */
@property(nonatomic, readwrite) int32_t src;

@property(nonatomic, readwrite) BOOL hasSrc;
@property(nonatomic, readwrite, copy, null_resettable) NSString *lastMsgTime;
/** Test to see if @c lastMsgTime has been set. */
@property(nonatomic, readwrite) BOOL hasLastMsgTime;

/** 微信号(未设置则显示wxid) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *alias;
/** Test to see if @c alias has been set. */
@property(nonatomic, readwrite) BOOL hasAlias;

@property(nonatomic, readwrite, copy, null_resettable) NSString *chatroomOwnerWxid;
/** Test to see if @c chatroomOwnerWxid has been set. */
@property(nonatomic, readwrite) BOOL hasChatroomOwnerWxid;

@property(nonatomic, readwrite) int32_t tag33;

@property(nonatomic, readwrite) BOOL hasTag33;
@property(nonatomic, readwrite) int32_t tag34;

@property(nonatomic, readwrite) BOOL hasTag34;
@property(nonatomic, readwrite) int32_t tag35;

@property(nonatomic, readwrite) BOOL hasTag35;
/** 个人相册封面图片 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *tag37;
/** Test to see if @c tag37 has been set. */
@property(nonatomic, readwrite) BOOL hasTag37;

@property(nonatomic, readwrite, copy, null_resettable) NSString *country;
/** Test to see if @c country has been set. */
@property(nonatomic, readwrite) BOOL hasCountry;

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatarBig;
/** Test to see if @c avatarBig has been set. */
@property(nonatomic, readwrite) BOOL hasAvatarBig;

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatarSmall;
/** Test to see if @c avatarSmall has been set. */
@property(nonatomic, readwrite) BOOL hasAvatarSmall;

@property(nonatomic, readwrite, copy, null_resettable) NSData *tag42;
/** Test to see if @c tag42 has been set. */
@property(nonatomic, readwrite) BOOL hasTag42;

/** encryptName(等价于wxid,固定不变) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *v1Name;
/** Test to see if @c v1Name has been set. */
@property(nonatomic, readwrite) BOOL hasV1Name;

@property(nonatomic, readwrite, copy, null_resettable) NSData *tag50;
/** Test to see if @c tag50 has been set. */
@property(nonatomic, readwrite) BOOL hasTag50;

@property(nonatomic, readwrite) int32_t chatroomServerVer;

@property(nonatomic, readwrite) BOOL hasChatroomServerVer;
@property(nonatomic, readwrite) int32_t chatroomMaxMember;

@property(nonatomic, readwrite) BOOL hasChatroomMaxMember;
@property(nonatomic, readwrite) int32_t tag56;

@property(nonatomic, readwrite) BOOL hasTag56;
@property(nonatomic, readwrite, strong, null_resettable) contact_info_GroupMemberList *groupMemberList;
/** Test to see if @c groupMemberList has been set. */
@property(nonatomic, readwrite) BOOL hasGroupMemberList;

@property(nonatomic, readwrite) int32_t tag58;

@property(nonatomic, readwrite) BOOL hasTag58;
@property(nonatomic, readwrite, copy, null_resettable) NSData *tag62;
/** Test to see if @c tag62 has been set. */
@property(nonatomic, readwrite) BOOL hasTag62;

@property(nonatomic, readwrite) int32_t tag64;

@property(nonatomic, readwrite) BOOL hasTag64;
@property(nonatomic, readwrite) int32_t tag65;

@property(nonatomic, readwrite) BOOL hasTag65;
@property(nonatomic, readwrite) int32_t tag66;

@property(nonatomic, readwrite) BOOL hasTag66;
@property(nonatomic, readwrite) int32_t tag67;

@property(nonatomic, readwrite) BOOL hasTag67;
@end

#pragma mark - contact_info_NickName

typedef GPB_ENUM(contact_info_NickName_FieldNumber) {
  contact_info_NickName_FieldNumber_Name = 1,
};

@interface contact_info_NickName : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

@end

#pragma mark - contact_info_PY_SHORT

typedef GPB_ENUM(contact_info_PY_SHORT_FieldNumber) {
  contact_info_PY_SHORT_FieldNumber_Name = 1,
};

@interface contact_info_PY_SHORT : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

@end

#pragma mark - contact_info_QuanPin

typedef GPB_ENUM(contact_info_QuanPin_FieldNumber) {
  contact_info_QuanPin_FieldNumber_Name = 1,
};

@interface contact_info_QuanPin : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

@end

#pragma mark - contact_info_BeiZhu

typedef GPB_ENUM(contact_info_BeiZhu_FieldNumber) {
  contact_info_BeiZhu_FieldNumber_Name = 1,
};

@interface contact_info_BeiZhu : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

@end

#pragma mark - contact_info_REAL_PY_SHORT

typedef GPB_ENUM(contact_info_REAL_PY_SHORT_FieldNumber) {
  contact_info_REAL_PY_SHORT_FieldNumber_Name = 1,
};

@interface contact_info_REAL_PY_SHORT : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

@end

#pragma mark - contact_info_REAL_QuanPin

typedef GPB_ENUM(contact_info_REAL_QuanPin_FieldNumber) {
  contact_info_REAL_QuanPin_FieldNumber_Name = 1,
};

@interface contact_info_REAL_QuanPin : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

@end

#pragma mark - contact_info_GroupMemberList

typedef GPB_ENUM(contact_info_GroupMemberList_FieldNumber) {
  contact_info_GroupMemberList_FieldNumber_Cnt = 1,
  contact_info_GroupMemberList_FieldNumber_MemberArray = 2,
  contact_info_GroupMemberList_FieldNumber_Tag3 = 3,
  contact_info_GroupMemberList_FieldNumber_Tag4 = 4,
};

@interface contact_info_GroupMemberList : GPBMessage

@property(nonatomic, readwrite) int32_t cnt;

@property(nonatomic, readwrite) BOOL hasCnt;
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<contact_info_GroupMemberList_MemberInfo*> *memberArray;
/** The number of items in @c memberArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger memberArray_Count;

@property(nonatomic, readwrite) int32_t tag3;

@property(nonatomic, readwrite) BOOL hasTag3;
@property(nonatomic, readwrite, copy, null_resettable) NSString *tag4;
/** Test to see if @c tag4 has been set. */
@property(nonatomic, readwrite) BOOL hasTag4;

@end

#pragma mark - contact_info_GroupMemberList_MemberInfo

typedef GPB_ENUM(contact_info_GroupMemberList_MemberInfo_FieldNumber) {
  contact_info_GroupMemberList_MemberInfo_FieldNumber_Wxid = 1,
  contact_info_GroupMemberList_MemberInfo_FieldNumber_NickName = 2,
  contact_info_GroupMemberList_MemberInfo_FieldNumber_Tag6 = 6,
  contact_info_GroupMemberList_MemberInfo_FieldNumber_InviteerWxid = 7,
  contact_info_GroupMemberList_MemberInfo_FieldNumber_Tag8 = 8,
};

@interface contact_info_GroupMemberList_MemberInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *wxid;
/** Test to see if @c wxid has been set. */
@property(nonatomic, readwrite) BOOL hasWxid;

/** 昵称(非群昵称) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *nickName;
/** Test to see if @c nickName has been set. */
@property(nonatomic, readwrite) BOOL hasNickName;

@property(nonatomic, readwrite) int32_t tag6;

@property(nonatomic, readwrite) BOOL hasTag6;
/** 邀请入群wxid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *inviteerWxid;
/** Test to see if @c inviteerWxid has been set. */
@property(nonatomic, readwrite) BOOL hasInviteerWxid;

@property(nonatomic, readwrite) int32_t tag8;

@property(nonatomic, readwrite) BOOL hasTag8;
@end

#pragma mark - common_msg

typedef GPB_ENUM(common_msg_FieldNumber) {
  common_msg_FieldNumber_Type = 1,
  common_msg_FieldNumber_Data_p = 2,
};

/**
 * 同步消息
 **/
@interface common_msg : GPBMessage

/** 消息类型:1==>个人信息,2==>好友信息,5==>服务器上未读取的最新消息,其余消息类型暂未知 */
@property(nonatomic, readwrite) int32_t type;

@property(nonatomic, readwrite) BOOL hasType;
@property(nonatomic, readwrite, strong, null_resettable) common_msg_Data *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - common_msg_Data

typedef GPB_ENUM(common_msg_Data_FieldNumber) {
  common_msg_Data_FieldNumber_Len = 1,
  common_msg_Data_FieldNumber_Data_p = 2,
};

@interface common_msg_Data : GPBMessage

@property(nonatomic, readwrite) int32_t len;

@property(nonatomic, readwrite) BOOL hasLen;
@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - NewInitResponse

typedef GPB_ENUM(NewInitResponse_FieldNumber) {
  NewInitResponse_FieldNumber_Tag1 = 1,
  NewInitResponse_FieldNumber_SyncKeyCur = 2,
  NewInitResponse_FieldNumber_SyncKeyMax = 3,
  NewInitResponse_FieldNumber_ContinueFlag = 4,
  NewInitResponse_FieldNumber_CntList = 6,
  NewInitResponse_FieldNumber_Tag7Array = 7,
};

/**
 * 新设备第一次登录初始化服务器响应
 **/
@interface NewInitResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *tag1;
/** Test to see if @c tag1 has been set. */
@property(nonatomic, readwrite) BOOL hasTag1;

/** 当前synckey二进制数据 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *syncKeyCur;
/** Test to see if @c syncKeyCur has been set. */
@property(nonatomic, readwrite) BOOL hasSyncKeyCur;

/** 最新synckey二进制数据(若与sync_key_cur不相同,则continue_flag返回1,表示需要继续初始化) */
@property(nonatomic, readwrite, copy, null_resettable) NSData *syncKeyMax;
/** Test to see if @c syncKeyMax has been set. */
@property(nonatomic, readwrite) BOOL hasSyncKeyMax;

/** 为1时表示仍要继续调用newinit初始化,直到该标志位返回0停止初始化(联系人或未读消息数据太多,无法一次获取完毕) */
@property(nonatomic, readwrite) int32_t continueFlag;

@property(nonatomic, readwrite) BOOL hasContinueFlag;
/** tag7结构体数量 */
@property(nonatomic, readwrite) int32_t cntList;

@property(nonatomic, readwrite) BOOL hasCntList;
/** 需要根据消息类型解析 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<common_msg*> *tag7Array;
/** The number of items in @c tag7Array without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tag7Array_Count;

@end

#pragma mark - NewSyncRequest

typedef GPB_ENUM(NewSyncRequest_FieldNumber) {
  NewSyncRequest_FieldNumber_Tag1 = 1,
  NewSyncRequest_FieldNumber_Selector = 2,
  NewSyncRequest_FieldNumber_KeyBuf = 3,
  NewSyncRequest_FieldNumber_Scene = 4,
  NewSyncRequest_FieldNumber_DeviceType = 5,
  NewSyncRequest_FieldNumber_SyncMsgDigest = 6,
};

/**
 * 同步消息
 **/
@interface NewSyncRequest : GPBMessage

/** unknown,must be 0 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *tag1;
/** Test to see if @c tag1 has been set. */
@property(nonatomic, readwrite) BOOL hasTag1;

/** unknown,just set 7 */
@property(nonatomic, readwrite) int32_t selector;

@property(nonatomic, readwrite) BOOL hasSelector;
/** 同步成功后服务器返回的消息id */
@property(nonatomic, readwrite, copy, null_resettable) NSData *keyBuf;
/** Test to see if @c keyBuf has been set. */
@property(nonatomic, readwrite) BOOL hasKeyBuf;

/** unkown,just set 3 */
@property(nonatomic, readwrite) int32_t scene;

@property(nonatomic, readwrite) BOOL hasScene;
/** 'android-22' */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceType;
/** Test to see if @c deviceType has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceType;

/** unknown,just set 1 */
@property(nonatomic, readwrite) int32_t syncMsgDigest;

@property(nonatomic, readwrite) BOOL hasSyncMsgDigest;
@end

#pragma mark - new_sync_resp

typedef GPB_ENUM(new_sync_resp_FieldNumber) {
  new_sync_resp_FieldNumber_Tag1 = 1,
  new_sync_resp_FieldNumber_Msg = 2,
  new_sync_resp_FieldNumber_Tag3 = 3,
  new_sync_resp_FieldNumber_SyncKey = 4,
  new_sync_resp_FieldNumber_Tag5 = 5,
  new_sync_resp_FieldNumber_Tag6 = 6,
  new_sync_resp_FieldNumber_Utc = 7,
};

/**
 * 同步消息响应
 **/
@interface new_sync_resp : GPBMessage

@property(nonatomic, readwrite) int32_t tag1;

@property(nonatomic, readwrite) BOOL hasTag1;
/** 未读消息 */
@property(nonatomic, readwrite, strong, null_resettable) new_sync_resp_new_msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@property(nonatomic, readwrite) int32_t tag3;

@property(nonatomic, readwrite) BOOL hasTag3;
/** 服务器返回的sync key */
@property(nonatomic, readwrite, copy, null_resettable) NSData *syncKey;
/** Test to see if @c syncKey has been set. */
@property(nonatomic, readwrite) BOOL hasSyncKey;

@property(nonatomic, readwrite) int32_t tag5;

@property(nonatomic, readwrite) BOOL hasTag5;
@property(nonatomic, readwrite) int32_t tag6;

@property(nonatomic, readwrite) BOOL hasTag6;
@property(nonatomic, readwrite) int32_t utc;

@property(nonatomic, readwrite) BOOL hasUtc;
@end

#pragma mark - new_sync_resp_new_msg

typedef GPB_ENUM(new_sync_resp_new_msg_FieldNumber) {
  new_sync_resp_new_msg_FieldNumber_CntList = 1,
  new_sync_resp_new_msg_FieldNumber_Tag2Array = 2,
};

@interface new_sync_resp_new_msg : GPBMessage

/** tag2结构体数量 */
@property(nonatomic, readwrite) int32_t cntList;

@property(nonatomic, readwrite) BOOL hasCntList;
/** 需要根据消息类型解析 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<common_msg*> *tag2Array;
/** The number of items in @c tag2Array without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tag2Array_Count;

@end

#pragma mark - MicroMsgRequestNew

typedef GPB_ENUM(MicroMsgRequestNew_FieldNumber) {
  MicroMsgRequestNew_FieldNumber_ToUserName = 1,
  MicroMsgRequestNew_FieldNumber_Content = 2,
  MicroMsgRequestNew_FieldNumber_Type = 3,
  MicroMsgRequestNew_FieldNumber_CreateTime = 4,
  MicroMsgRequestNew_FieldNumber_ClientMsgId = 5,
  MicroMsgRequestNew_FieldNumber_MsgSource = 6,
};

@interface MicroMsgRequestNew : GPBMessage

/** to wxid */
@property(nonatomic, readwrite, strong, null_resettable) SKBuiltinString_t *toUserName;
/** Test to see if @c toUserName has been set. */
@property(nonatomic, readwrite) BOOL hasToUserName;

/** 消息内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;
/** Test to see if @c content has been set. */
@property(nonatomic, readwrite) BOOL hasContent;

/** 消息类型: 文字消息=>1,名片=>42， */
@property(nonatomic, readwrite) int32_t type;

@property(nonatomic, readwrite) BOOL hasType;
/** 1537268848 */
@property(nonatomic, readwrite) int32_t createTime;

@property(nonatomic, readwrite) BOOL hasCreateTime;
/** 不同消息的utc与client_id必须至少有1个不相同 4287068409, iMac 从1开始？ */
@property(nonatomic, readwrite) int64_t clientMsgId;

@property(nonatomic, readwrite) BOOL hasClientMsgId;
/** 群聊at功能 iMac: "<msgsource></msgsource>" */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgSource;
/** Test to see if @c msgSource has been set. */
@property(nonatomic, readwrite) BOOL hasMsgSource;

@end

#pragma mark - SendMsgRequestNew

typedef GPB_ENUM(SendMsgRequestNew_FieldNumber) {
  SendMsgRequestNew_FieldNumber_Count = 1,
  SendMsgRequestNew_FieldNumber_ListArray = 2,
};

/**
 * 发送消息请求
 **/
@interface SendMsgRequestNew : GPBMessage

/** 本次发送的消息数量 */
@property(nonatomic, readwrite) int32_t count;

@property(nonatomic, readwrite) BOOL hasCount;
/** 这里可以是repeated,允许一次发送多条消息 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MicroMsgRequestNew*> *listArray;
/** The number of items in @c listArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

#pragma mark - MicroMsgResponseNew

typedef GPB_ENUM(MicroMsgResponseNew_FieldNumber) {
  MicroMsgResponseNew_FieldNumber_Ret = 1,
  MicroMsgResponseNew_FieldNumber_ToUserName = 2,
  MicroMsgResponseNew_FieldNumber_MsgId = 3,
  MicroMsgResponseNew_FieldNumber_ClientMsgId = 4,
  MicroMsgResponseNew_FieldNumber_CreateTime = 5,
  MicroMsgResponseNew_FieldNumber_ServerTime = 6,
  MicroMsgResponseNew_FieldNumber_Type = 7,
  MicroMsgResponseNew_FieldNumber_NewMsgId = 8,
};

@interface MicroMsgResponseNew : GPBMessage

/** 错误码 0=>发送成功,-44=>对方开启了朋友验证(被删好友),-22=>消息已发出,但被对方拒收了(被拉黑) */
@property(nonatomic, readwrite) int32_t ret;

@property(nonatomic, readwrite) BOOL hasRet;
/** to wxid */
@property(nonatomic, readwrite, strong, null_resettable) SKBuiltinString_t *toUserName;
/** Test to see if @c toUserName has been set. */
@property(nonatomic, readwrite) BOOL hasToUserName;

@property(nonatomic, readwrite) int32_t msgId;

@property(nonatomic, readwrite) BOOL hasMsgId;
@property(nonatomic, readwrite) int32_t clientMsgId;

@property(nonatomic, readwrite) BOOL hasClientMsgId;
@property(nonatomic, readwrite) int32_t createTime;

@property(nonatomic, readwrite) BOOL hasCreateTime;
@property(nonatomic, readwrite) int32_t serverTime;

@property(nonatomic, readwrite) BOOL hasServerTime;
/** 消息类型 */
@property(nonatomic, readwrite) int32_t type;

@property(nonatomic, readwrite) BOOL hasType;
/** 消息唯一id */
@property(nonatomic, readwrite) int64_t newMsgId;

@property(nonatomic, readwrite) BOOL hasNewMsgId;
@end

#pragma mark - SendMsgResponseNew

typedef GPB_ENUM(SendMsgResponseNew_FieldNumber) {
  SendMsgResponseNew_FieldNumber_BaseResponse = 1,
  SendMsgResponseNew_FieldNumber_Count = 2,
  SendMsgResponseNew_FieldNumber_ListArray = 3,
};

/**
 * 发送消息响应
 **/
@interface SendMsgResponseNew : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@property(nonatomic, readwrite) int32_t count;

@property(nonatomic, readwrite) BOOL hasCount;
/** 发送结 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MicroMsgResponseNew*> *listArray;
/** The number of items in @c listArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

#pragma mark - CheckResUpdateRequest

typedef GPB_ENUM(CheckResUpdateRequest_FieldNumber) {
  CheckResUpdateRequest_FieldNumber_ResIdArray = 1,
};

@interface CheckResUpdateRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<CheckResUpdateRequest_ResID*> *resIdArray;
/** The number of items in @c resIdArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger resIdArray_Count;

@end

#pragma mark - CheckResUpdateRequest_ResID

typedef GPB_ENUM(CheckResUpdateRequest_ResID_FieldNumber) {
  CheckResUpdateRequest_ResID_FieldNumber_Type = 1,
  CheckResUpdateRequest_ResID_FieldNumber_SubTypeVectorArray = 2,
};

@interface CheckResUpdateRequest_ResID : GPBMessage

@property(nonatomic, readwrite) int32_t type;

@property(nonatomic, readwrite) BOOL hasType;
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<CheckResUpdateRequest_ResID_SubTypeVector*> *subTypeVectorArray;
/** The number of items in @c subTypeVectorArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger subTypeVectorArray_Count;

@end

#pragma mark - CheckResUpdateRequest_ResID_SubTypeVector

typedef GPB_ENUM(CheckResUpdateRequest_ResID_SubTypeVector_FieldNumber) {
  CheckResUpdateRequest_ResID_SubTypeVector_FieldNumber_SubType = 1,
  CheckResUpdateRequest_ResID_SubTypeVector_FieldNumber_KeyVersion = 2,
  CheckResUpdateRequest_ResID_SubTypeVector_FieldNumber_ResVersion = 3,
  CheckResUpdateRequest_ResID_SubTypeVector_FieldNumber_Eid = 4,
};

@interface CheckResUpdateRequest_ResID_SubTypeVector : GPBMessage

@property(nonatomic, readwrite) int32_t subType;

@property(nonatomic, readwrite) BOOL hasSubType;
@property(nonatomic, readwrite) int32_t keyVersion;

@property(nonatomic, readwrite) BOOL hasKeyVersion;
@property(nonatomic, readwrite) int32_t resVersion;

@property(nonatomic, readwrite) BOOL hasResVersion;
@property(nonatomic, readwrite) int32_t eid;

@property(nonatomic, readwrite) BOOL hasEid;
@end

#pragma mark - SnsObject

typedef GPB_ENUM(SnsObject_FieldNumber) {
  SnsObject_FieldNumber_Id_p = 1,
  SnsObject_FieldNumber_Username = 2,
  SnsObject_FieldNumber_Nickname = 3,
  SnsObject_FieldNumber_CreateTime = 4,
  SnsObject_FieldNumber_ObjectDesc = 5,
  SnsObject_FieldNumber_ExtFlag = 16,
  SnsObject_FieldNumber_ObjectOperations = 28,
};

@interface SnsObject : GPBMessage

/** 12944632620798980176 */
@property(nonatomic, readwrite) uint64_t id_p;

@property(nonatomic, readwrite) BOOL hasId_p;
/** wxid_19py48yw39qw22 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *username;
/** Test to see if @c username has been set. */
@property(nonatomic, readwrite) BOOL hasUsername;

/** xiaohao */
@property(nonatomic, readwrite, copy, null_resettable) NSString *nickname;
/** Test to see if @c nickname has been set. */
@property(nonatomic, readwrite) BOOL hasNickname;

/** 1543120458 */
@property(nonatomic, readwrite) int32_t createTime;

@property(nonatomic, readwrite) BOOL hasCreateTime;
@property(nonatomic, readwrite, strong, null_resettable) SKBuiltinBuffer_t *objectDesc;
/** Test to see if @c objectDesc has been set. */
@property(nonatomic, readwrite) BOOL hasObjectDesc;

@property(nonatomic, readwrite) int32_t extFlag;

@property(nonatomic, readwrite) BOOL hasExtFlag;
@property(nonatomic, readwrite, strong, null_resettable) SKBuiltinString_t *objectOperations;
/** Test to see if @c objectOperations has been set. */
@property(nonatomic, readwrite) BOOL hasObjectOperations;

@end

#pragma mark - SnsTimeLineRequest

typedef GPB_ENUM(SnsTimeLineRequest_FieldNumber) {
  SnsTimeLineRequest_FieldNumber_BaseRequest = 1,
  SnsTimeLineRequest_FieldNumber_FirstPageMd5 = 2,
  SnsTimeLineRequest_FieldNumber_MinFilterId = 3,
  SnsTimeLineRequest_FieldNumber_MaxId = 4,
  SnsTimeLineRequest_FieldNumber_LastRequestTime = 5,
  SnsTimeLineRequest_FieldNumber_ClientLatestId = 6,
  SnsTimeLineRequest_FieldNumber_Session = 7,
  SnsTimeLineRequest_FieldNumber_NetworkType = 8,
  SnsTimeLineRequest_FieldNumber_Adexpinfo = 10,
};

@interface SnsTimeLineRequest : GPBMessage

/** iOS不用设置 */
@property(nonatomic, readwrite, strong, null_resettable) BaseRequest *baseRequest;
/** Test to see if @c baseRequest has been set. */
@property(nonatomic, readwrite) BOOL hasBaseRequest;

@property(nonatomic, readwrite, copy, null_resettable) NSString *firstPageMd5;
/** Test to see if @c firstPageMd5 has been set. */
@property(nonatomic, readwrite) BOOL hasFirstPageMd5;

@property(nonatomic, readwrite) int32_t minFilterId;

@property(nonatomic, readwrite) BOOL hasMinFilterId;
@property(nonatomic, readwrite) int32_t maxId;

@property(nonatomic, readwrite) BOOL hasMaxId;
@property(nonatomic, readwrite) int32_t lastRequestTime;

@property(nonatomic, readwrite) BOOL hasLastRequestTime;
@property(nonatomic, readwrite) int64_t clientLatestId;

@property(nonatomic, readwrite) BOOL hasClientLatestId;
@property(nonatomic, readwrite, strong, null_resettable) SKBuiltinBuffer_t *session;
/** Test to see if @c session has been set. */
@property(nonatomic, readwrite) BOOL hasSession;

@property(nonatomic, readwrite) int32_t networkType;

@property(nonatomic, readwrite) BOOL hasNetworkType;
/** "" */
@property(nonatomic, readwrite, copy, null_resettable) NSString *adexpinfo;
/** Test to see if @c adexpinfo has been set. */
@property(nonatomic, readwrite) BOOL hasAdexpinfo;

@end

#pragma mark - SnsTimeLineResponse

typedef GPB_ENUM(SnsTimeLineResponse_FieldNumber) {
  SnsTimeLineResponse_FieldNumber_BaseResponse = 1,
  SnsTimeLineResponse_FieldNumber_FirstPageMd5 = 2,
  SnsTimeLineResponse_FieldNumber_ObjectCount = 3,
  SnsTimeLineResponse_FieldNumber_ObjectListArray = 4,
  SnsTimeLineResponse_FieldNumber_NewRequestTime = 5,
  SnsTimeLineResponse_FieldNumber_ObjectCountForSameMd5 = 6,
  SnsTimeLineResponse_FieldNumber_ControlFlag = 7,
  SnsTimeLineResponse_FieldNumber_ServerConfig = 8,
  SnsTimeLineResponse_FieldNumber_RecCount = 9,
  SnsTimeLineResponse_FieldNumber_Session = 11,
};

@interface SnsTimeLineResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@property(nonatomic, readwrite, copy, null_resettable) NSString *firstPageMd5;
/** Test to see if @c firstPageMd5 has been set. */
@property(nonatomic, readwrite) BOOL hasFirstPageMd5;

@property(nonatomic, readwrite) int32_t objectCount;

@property(nonatomic, readwrite) BOOL hasObjectCount;
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SnsObject*> *objectListArray;
/** The number of items in @c objectListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger objectListArray_Count;

@property(nonatomic, readwrite) int32_t newRequestTime;

@property(nonatomic, readwrite) BOOL hasNewRequestTime;
@property(nonatomic, readwrite) int32_t objectCountForSameMd5;

@property(nonatomic, readwrite) BOOL hasObjectCountForSameMd5;
@property(nonatomic, readwrite) int32_t controlFlag;

@property(nonatomic, readwrite) BOOL hasControlFlag;
@property(nonatomic, readwrite, strong, null_resettable) SnsTimeLineResponse_SnsServerConfig *serverConfig;
/** Test to see if @c serverConfig has been set. */
@property(nonatomic, readwrite) BOOL hasServerConfig;

@property(nonatomic, readwrite) int32_t recCount;

@property(nonatomic, readwrite) BOOL hasRecCount;
/** repeated recList                      = 10; */
@property(nonatomic, readwrite, copy, null_resettable) NSData *session;
/** Test to see if @c session has been set. */
@property(nonatomic, readwrite) BOOL hasSession;

@end

#pragma mark - SnsTimeLineResponse_SnsServerConfig

typedef GPB_ENUM(SnsTimeLineResponse_SnsServerConfig_FieldNumber) {
  SnsTimeLineResponse_SnsServerConfig_FieldNumber_PostMentionLimit = 1,
  SnsTimeLineResponse_SnsServerConfig_FieldNumber_CopyAndPasteWordLimit = 2,
};

@interface SnsTimeLineResponse_SnsServerConfig : GPBMessage

@property(nonatomic, readwrite) int32_t postMentionLimit;

@property(nonatomic, readwrite) BOOL hasPostMentionLimit;
@property(nonatomic, readwrite) int32_t copyAndPasteWordLimit;

@property(nonatomic, readwrite) BOOL hasCopyAndPasteWordLimit;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
